#include "render/optix_renderer.h"

#include <optix.h>
#include <optix_function_table_definition.h>
#include <optix_stack_size.h>
#include <optix_stubs.h>

#include <cuda_gl_interop.h>
#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <sstream>
#include <vector>

#include <sutil/vec_math.h> // float3 operators/cross/normalize — see buildModule() for why this is safe on the host

#include "convert/gsplat_bounds.h"
#include "convert/voxel_grid.h"
#include "io/gsplat_asset.h"
#include "render/gl_ext.h"
#include "render/kernels/pathtracer_params.h"
#include "render/optix_check.h"
#include "render_config.h" // generated by CMake: kPathTracerOptixIRPath

namespace italy {
namespace {

float3 toFloat3(const glm::vec3 &v) { return make_float3(v.x, v.y, v.z); }

template <typename T> struct SbtRecord {
  __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
  T data;
};
using RayGenRecord = SbtRecord<RayGenData>;
using MissRecord = SbtRecord<MissData>;
using HitGroupRecord = SbtRecord<HitGroupData>;

std::vector<char> readFile(const char *path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f)
    throw std::runtime_error(std::string("cannot open ") + path);
  const auto size = f.tellg();
  std::vector<char> data(static_cast<size_t>(size));
  f.seekg(0);
  f.read(data.data(), size);
  return data;
}

void contextLogCallback(unsigned int level, const char *tag, const char *message, void *) {
  std::fprintf(stderr, "[optix][%u][%s] %s\n", level, tag, message);
}

// Sphere      = OptiX built-in sphere primitive. Hardware path, but hollow
//               and back-face culled, so it can only carry opaque materials.
// SolidSphere = custom-primitive sphere with our own intersector, which does
//               report exit hits. Required for dielectrics — see
//               __intersection__sphere_solid in pathtracer.cu.
enum class GeometryKind { Triangle, Sphere, SolidSphere, Voxel, Sdf, Gsplat };

// One static-geometry object in the scene: a GAS (built once) plus the
// material record it contributes to the SBT. `kind` selects which hit-group
// program group (and thus which intersection program) the object's SBT
// record is packed against.
struct SceneObject {
  OptixTraversableHandle gas = 0;
  CUdeviceptr gasBuffer = 0;
  HitGroupData material{};
  GeometryKind kind = GeometryKind::Triangle;
};

} // namespace

struct OptixRenderer::Impl {
  OptixDeviceContext context = nullptr;
  OptixModule module = nullptr;
  OptixModule sphereModule = nullptr;
  OptixPipelineCompileOptions pipelineCompileOptions{};

  OptixProgramGroup raygenPG = nullptr;
  OptixProgramGroup missRadiancePG = nullptr;
  OptixProgramGroup missOcclusionPG = nullptr;
  OptixProgramGroup hitTrianglePG = nullptr;
  OptixProgramGroup hitSpherePG = nullptr;
  OptixProgramGroup hitSolidSpherePG = nullptr;
  OptixProgramGroup hitVoxelPG = nullptr;
  OptixProgramGroup hitSdfPG = nullptr;
  OptixProgramGroup hitGsplatPG = nullptr;

  // VCM Step 1 (see /home/joe/.claude/plans/what-is-the-next-wise-flurry.md):
  // a second SBT (lightSubpathSbt) sharing this same pipeline/context, used
  // only for the light-subpath-emission launch — see buildLightSubpathSbt()'s
  // comment for why a second SBT rather than ray-type-multiplexing the
  // existing one. Replaces the old phase-7 photon pipeline's equivalent
  // program groups; there is deliberately no gatherHitPG/gatherMissPG
  // equivalent here — Step 1 has no vertex *merging* (that gather-style
  // range query is Step 2's job), so __closesthit__radiance just walks
  // params.lightVertices as a plain array instead of tracing into a GAS.
  OptixProgramGroup lightSubpathRaygenPG = nullptr;
  OptixProgramGroup lightSubpathMissPG = nullptr;
  OptixProgramGroup lightSubpathHitTrianglePG = nullptr;
  OptixProgramGroup lightSubpathHitSpherePG = nullptr;
  OptixProgramGroup lightSubpathHitSolidSpherePG = nullptr;

  // Phase 10 denoiser: __raygen__tonemap is a third raygen-only launch (its
  // own minimal SBT, no miss/hitgroup records — it never calls optixTrace)
  // that reads the denoiser's output into the display buffer. Same "reuse
  // the existing module/pipeline instead of a new CUDA compilation unit"
  // reasoning as photon emission's second SBT.
  OptixProgramGroup tonemapRaygenPG = nullptr;
  OptixShaderBindingTable tonemapSbt{};
  OptixDenoiser denoiser = nullptr;
  CUdeviceptr denoiserStateBuffer = 0;
  size_t denoiserStateSize = 0;
  CUdeviceptr denoiserScratchBuffer = 0;
  size_t denoiserScratchSize = 0;
  CUdeviceptr denoisedBuffer = 0; // float4 * width*height

  OptixPipeline pipeline = nullptr;

  std::vector<SceneObject> objects;
  OptixTraversableHandle iasHandle = 0;
  CUdeviceptr iasBuffer = 0;

  OptixShaderBindingTable sbt{};

  CUstream stream = nullptr;
  CUdeviceptr accumBuffer = 0; // float4 * width*height
  CUdeviceptr paramsBuffer = 0;

  // GL/CUDA interop: CUDA writes the tonemapped frame directly into a mapped
  // pixel-unpack buffer; glTexSubImage2D uploads it from there with no extra
  // device-to-host round trip.
  unsigned int pbo = 0;
  cudaGraphicsResource *cudaPbo = nullptr;

  QuadLight light{};
  glm::vec3 boundsCenter{0.0f};
  float boundsRadius = 3.0f;

  // Device buffers backing a MATERIAL_TEXTURED_DIFFUSE object's per-vertex
  // attributes, per-triangle material index, and material/texture tables —
  // freed in destroy().
  CUdeviceptr meshNormals = 0;
  CUdeviceptr meshUvs = 0;
  CUdeviceptr meshTangents = 0;
  CUdeviceptr meshTriangleMaterial = 0;
  CUdeviceptr meshMaterials = 0;
  std::vector<cudaArray_t> textureArrays;
  std::vector<cudaTextureObject_t> textureObjects;

  // Device buffers backing a MATERIAL_VOXEL object's per-primitive AABBs
  // (also feeds __intersection__voxel) and baked colors — freed in destroy().
  CUdeviceptr voxelAabbBuffer = 0;
  CUdeviceptr voxelColorBuffer = 0;

  // Device buffer backing a MATERIAL_SDF object's dense distance field —
  // freed in destroy().
  CUdeviceptr sdfDistanceBuffer = 0;

  // Device buffers backing a MATERIAL_GSPLAT object's per-primitive
  // position/scale/rotation/opacity/color arrays — freed in destroy(). No
  // AABB buffer kept alive: unlike voxels, __intersection__gsplat re-derives
  // the ellipsoid from these directly rather than re-reading a box.
  CUdeviceptr splatPositionBuffer = 0;
  CUdeviceptr splatScaleBuffer = 0;
  CUdeviceptr splatRotationBuffer = 0;
  CUdeviceptr splatOpacityBuffer = 0;
  CUdeviceptr splatColorBuffer = 0;

  // Environment/HDRI lighting (phase 6) — freed in destroy(). hasEnvironment
  // gates whether buildFixedTestScene/buildMeshScene/etc add a quad light at
  // all (see addBoundsKeyLight): the two lighting modes aren't blended.
  bool hasEnvironment = false;
  bool wantGroundPlane = true;
  cudaArray_t envArray = nullptr;
  cudaTextureObject_t envTexObj = 0;
  CUdeviceptr envMarginalCdfBuffer = 0;
  CUdeviceptr envConditionalCdfBuffer = 0;
  int envWidth = 0;
  int envHeight = 0;

  // VCM Step 1 light subpaths (see
  // /home/joe/.claude/plans/what-is-the-next-wise-flurry.md). Replaces the
  // old phase-7 photon/SPPM pipeline entirely. Built for the fixed test
  // scene (always has specular/glass objects) and, since the
  // watertight-mesh gate made triangle-mesh dielectrics trustworthy, for a
  // loaded mesh scene too — but only when it actually has a material that
  // can seed one (see buildMeshScene's scan): building the whole
  // light-subpath pipeline/SBT for an all-Lambert asset would cost a pass
  // per frame for a permanently-empty vertex buffer. Voxel/SDF/gsplat scenes
  // still never qualify (no per-primitive material to test, and stay
  // eye-path-only per the VCM plan's explicit scope boundary either way).
  //
  // kLightSubpathBatchSize is deliberately much smaller than the old photon
  // pass's 65536: __closesthit__radiance's BDPT connection loop is O(stored
  // vertices) *per diffuse eye hit*, with no spatial culling yet (that's
  // vertex merging, Step 2's job) — a batch this size keeps that loop
  // tractable for interactive use while Step 1 is unweighted/unpruned; Step
  // 4 is where a real connection-count cap or subsampling scheme lands.
  //
  // claudia: quick tuning pass (caustics reported too dim vs. sdf-noon.png)
  // — raised 512->2048 (capacity kept at the same ~16x-of-batch headroom
  // ratio) to feed more light subpaths into Step 1's unmerged BDPT
  // connections per frame, at a proportional per-frame cost. This does not
  // address the actual gap (no vertex merging / Lambertian-only connections,
  // Steps 2-3 of the VCM plan) — it only strengthens what Step 1 already
  // computes. Revert or retune once Step 2 lands and this loop gets spatial
  // culling.
  bool enableLightSubpaths = false;
  static constexpr unsigned int kLightSubpathBatchSize = 2048;
  static constexpr unsigned int kLightVertexCapacity = 32768; // headroom over batchSize * the 12-bounce depth cap
  OptixShaderBindingTable lightSubpathSbt{};
  CUdeviceptr lightVertexBuffer = 0;        // LightVertex[kLightVertexCapacity]
  CUdeviceptr lightVertexCounterBuffer = 0; // single atomic uint
  unsigned int lightSubpathPassIndex = 0;
  unsigned int totalLightPathsEmitted = 0;

  ~Impl() { destroy(); }

  void destroy() {
    for (cudaTextureObject_t obj : textureObjects)
      if (obj)
        cudaDestroyTextureObject(obj);
    for (cudaArray_t arr : textureArrays)
      if (arr)
        cudaFreeArray(arr);
    if (meshNormals)
      cudaFree(reinterpret_cast<void *>(meshNormals));
    if (meshUvs)
      cudaFree(reinterpret_cast<void *>(meshUvs));
    if (meshTangents)
      cudaFree(reinterpret_cast<void *>(meshTangents));
    if (meshTriangleMaterial)
      cudaFree(reinterpret_cast<void *>(meshTriangleMaterial));
    if (meshMaterials)
      cudaFree(reinterpret_cast<void *>(meshMaterials));
    if (voxelAabbBuffer)
      cudaFree(reinterpret_cast<void *>(voxelAabbBuffer));
    if (voxelColorBuffer)
      cudaFree(reinterpret_cast<void *>(voxelColorBuffer));
    if (sdfDistanceBuffer)
      cudaFree(reinterpret_cast<void *>(sdfDistanceBuffer));
    if (splatPositionBuffer)
      cudaFree(reinterpret_cast<void *>(splatPositionBuffer));
    if (splatScaleBuffer)
      cudaFree(reinterpret_cast<void *>(splatScaleBuffer));
    if (splatRotationBuffer)
      cudaFree(reinterpret_cast<void *>(splatRotationBuffer));
    if (splatOpacityBuffer)
      cudaFree(reinterpret_cast<void *>(splatOpacityBuffer));
    if (splatColorBuffer)
      cudaFree(reinterpret_cast<void *>(splatColorBuffer));
    if (envTexObj)
      cudaDestroyTextureObject(envTexObj);
    if (envArray)
      cudaFreeArray(envArray);
    if (envMarginalCdfBuffer)
      cudaFree(reinterpret_cast<void *>(envMarginalCdfBuffer));
    if (envConditionalCdfBuffer)
      cudaFree(reinterpret_cast<void *>(envConditionalCdfBuffer));
    if (lightVertexBuffer)
      cudaFree(reinterpret_cast<void *>(lightVertexBuffer));
    if (lightVertexCounterBuffer)
      cudaFree(reinterpret_cast<void *>(lightVertexCounterBuffer));
    if (lightSubpathSbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(lightSubpathSbt.raygenRecord));
    if (lightSubpathSbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(lightSubpathSbt.missRecordBase));
    if (lightSubpathSbt.hitgroupRecordBase)
      cudaFree(reinterpret_cast<void *>(lightSubpathSbt.hitgroupRecordBase));
    if (tonemapSbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(tonemapSbt.raygenRecord));
    if (tonemapSbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(tonemapSbt.missRecordBase));
    if (denoisedBuffer)
      cudaFree(reinterpret_cast<void *>(denoisedBuffer));
    if (denoiserStateBuffer)
      cudaFree(reinterpret_cast<void *>(denoiserStateBuffer));
    if (denoiserScratchBuffer)
      cudaFree(reinterpret_cast<void *>(denoiserScratchBuffer));
    if (denoiser)
      optixDenoiserDestroy(denoiser);
    if (paramsBuffer)
      cudaFree(reinterpret_cast<void *>(paramsBuffer));
    if (accumBuffer)
      cudaFree(reinterpret_cast<void *>(accumBuffer));
    if (sbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(sbt.raygenRecord));
    if (sbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(sbt.missRecordBase));
    if (sbt.hitgroupRecordBase)
      cudaFree(reinterpret_cast<void *>(sbt.hitgroupRecordBase));
    if (iasBuffer)
      cudaFree(reinterpret_cast<void *>(iasBuffer));
    for (auto &obj : objects)
      if (obj.gasBuffer)
        cudaFree(reinterpret_cast<void *>(obj.gasBuffer));
    if (cudaPbo)
      cudaGraphicsUnregisterResource(cudaPbo);
    if (pbo)
      GLBufferFns::get().glDeleteBuffers(1, &pbo);
    if (pipeline)
      optixPipelineDestroy(pipeline);
    if (tonemapRaygenPG)
      optixProgramGroupDestroy(tonemapRaygenPG);
    if (lightSubpathHitSolidSpherePG)
      optixProgramGroupDestroy(lightSubpathHitSolidSpherePG);
    if (lightSubpathHitSpherePG)
      optixProgramGroupDestroy(lightSubpathHitSpherePG);
    if (lightSubpathHitTrianglePG)
      optixProgramGroupDestroy(lightSubpathHitTrianglePG);
    if (lightSubpathMissPG)
      optixProgramGroupDestroy(lightSubpathMissPG);
    if (lightSubpathRaygenPG)
      optixProgramGroupDestroy(lightSubpathRaygenPG);
    if (hitGsplatPG)
      optixProgramGroupDestroy(hitGsplatPG);
    if (hitSdfPG)
      optixProgramGroupDestroy(hitSdfPG);
    if (hitVoxelPG)
      optixProgramGroupDestroy(hitVoxelPG);
    if (hitSolidSpherePG)
      optixProgramGroupDestroy(hitSolidSpherePG);
    if (hitSpherePG)
      optixProgramGroupDestroy(hitSpherePG);
    if (hitTrianglePG)
      optixProgramGroupDestroy(hitTrianglePG);
    if (missOcclusionPG)
      optixProgramGroupDestroy(missOcclusionPG);
    if (missRadiancePG)
      optixProgramGroupDestroy(missRadiancePG);
    if (raygenPG)
      optixProgramGroupDestroy(raygenPG);
    if (sphereModule)
      optixModuleDestroy(sphereModule);
    if (module)
      optixModuleDestroy(module);
    if (context)
      optixDeviceContextDestroy(context);
  }

  void initContext() {
    CUDA_CHECK(cudaFree(nullptr)); // establish the primary CUDA context
    OPTIX_CHECK(optixInit());
    OptixDeviceContextOptions options{};
    options.logCallbackFunction = &contextLogCallback;
    options.logCallbackLevel = 3;
    OPTIX_CHECK(optixDeviceContextCreate(nullptr, &options, &context));
    CUDA_CHECK(cudaStreamCreate(&stream));
  }

  void buildModule() {
    pipelineCompileOptions.usesMotionBlur = false;
    pipelineCompileOptions.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_LEVEL_INSTANCING;
    pipelineCompileOptions.numPayloadValues = 19;
    pipelineCompileOptions.numAttributeValues = 2;
    pipelineCompileOptions.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    pipelineCompileOptions.pipelineLaunchParamsVariableName = "params";
    pipelineCompileOptions.usesPrimitiveTypeFlags =
        OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE | OPTIX_PRIMITIVE_TYPE_FLAGS_SPHERE | OPTIX_PRIMITIVE_TYPE_FLAGS_CUSTOM;

    OptixModuleCompileOptions moduleOptions{};
    moduleOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_3;
    moduleOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;

    const std::vector<char> ir = readFile(kPathTracerOptixIRPath);
    OPTIX_CHECK_LOG(optixModuleCreate(context, &moduleOptions, &pipelineCompileOptions, ir.data(), ir.size(), LOG,
                                       &LOG_SIZE, &module));

    OptixBuiltinISOptions sphereOpts{};
    sphereOpts.usesMotionBlur = false;
    sphereOpts.builtinISModuleType = OPTIX_PRIMITIVE_TYPE_SPHERE;
    OPTIX_CHECK_LOG(
        optixBuiltinISModuleGet(context, &moduleOptions, &pipelineCompileOptions, &sphereOpts, &sphereModule));
  }

  void buildProgramGroups() {
    OptixProgramGroupOptions pgOptions{};

    OptixProgramGroupDesc raygenDesc{};
    raygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    raygenDesc.raygen.module = module;
    raygenDesc.raygen.entryFunctionName = "__raygen__rg";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &raygenDesc, 1, &pgOptions, LOG, &LOG_SIZE, &raygenPG));

    OptixProgramGroupDesc missRadDesc{};
    missRadDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    missRadDesc.miss.module = module;
    missRadDesc.miss.entryFunctionName = "__miss__radiance";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &missRadDesc, 1, &pgOptions, LOG, &LOG_SIZE, &missRadiancePG));

    OptixProgramGroupDesc missOccDesc{};
    missOccDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    missOccDesc.miss.module = module;
    missOccDesc.miss.entryFunctionName = "__miss__occlusion";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &missOccDesc, 1, &pgOptions, LOG, &LOG_SIZE, &missOcclusionPG));

    OptixProgramGroupDesc hitTriDesc{};
    hitTriDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitTriDesc.hitgroup.moduleCH = module;
    hitTriDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    // Triangle intersection is built into OptiX; no IS module needed.
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitTriDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitTrianglePG));

    OptixProgramGroupDesc hitSphereDesc{};
    hitSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitSphereDesc.hitgroup.moduleCH = module;
    hitSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitSphereDesc.hitgroup.moduleIS = sphereModule;
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitSpherePG));

    // Dielectrics: our own sphere intersector (the built-in one is hollow).
    OptixProgramGroupDesc hitSolidSphereDesc{};
    hitSolidSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitSolidSphereDesc.hitgroup.moduleCH = module;
    hitSolidSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitSolidSphereDesc.hitgroup.moduleIS = module;
    hitSolidSphereDesc.hitgroup.entryFunctionNameIS = "__intersection__sphere_solid";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &hitSolidSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitSolidSpherePG));

    OptixProgramGroupDesc hitVoxelDesc{};
    hitVoxelDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitVoxelDesc.hitgroup.moduleCH = module;
    hitVoxelDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    // Custom (non-builtin) primitive — our own intersection program, same
    // module as everything else since it's compiled from pathtracer.cu too.
    hitVoxelDesc.hitgroup.moduleIS = module;
    hitVoxelDesc.hitgroup.entryFunctionNameIS = "__intersection__voxel";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitVoxelDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitVoxelPG));

    OptixProgramGroupDesc hitSdfDesc{};
    hitSdfDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitSdfDesc.hitgroup.moduleCH = module;
    hitSdfDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitSdfDesc.hitgroup.moduleIS = module;
    hitSdfDesc.hitgroup.entryFunctionNameIS = "__intersection__sdf";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitSdfDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitSdfPG));

    // Roadmap phase 3: imported Gaussian splats. Custom-primitive ellipsoid
    // intersection plus an any-hit for the stochastic alpha test (see
    // MATERIAL_GSPLAT's doc comment in pathtracer_params.h) — the only hit
    // group in this renderer that needs all three of IS/AH/CH.
    OptixProgramGroupDesc hitGsplatDesc{};
    hitGsplatDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitGsplatDesc.hitgroup.moduleCH = module;
    hitGsplatDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitGsplatDesc.hitgroup.moduleAH = module;
    hitGsplatDesc.hitgroup.entryFunctionNameAH = "__anyhit__gsplat";
    hitGsplatDesc.hitgroup.moduleIS = module;
    hitGsplatDesc.hitgroup.entryFunctionNameIS = "__intersection__gsplat";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitGsplatDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitGsplatPG));

    // VCM Step 1: light-subpath emission (own raygen/miss, reuses the
    // triangle/sphere IS modules already built above). No gather-style
    // any-hit query here — Step 1 has no vertex merging, so
    // __closesthit__radiance's BDPT connections just walk
    // params.lightVertices as a plain array (see that comment).
    OptixProgramGroupDesc lightSubpathRaygenDesc{};
    lightSubpathRaygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    lightSubpathRaygenDesc.raygen.module = module;
    lightSubpathRaygenDesc.raygen.entryFunctionName = "__raygen__lightSubpath";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &lightSubpathRaygenDesc, 1, &pgOptions, LOG, &LOG_SIZE,
                                             &lightSubpathRaygenPG));

    OptixProgramGroupDesc lightSubpathMissDesc{};
    lightSubpathMissDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    lightSubpathMissDesc.miss.module = module;
    lightSubpathMissDesc.miss.entryFunctionName = "__miss__lightSubpath";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &lightSubpathMissDesc, 1, &pgOptions, LOG, &LOG_SIZE, &lightSubpathMissPG));

    OptixProgramGroupDesc lightSubpathHitTriDesc{};
    lightSubpathHitTriDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    lightSubpathHitTriDesc.hitgroup.moduleCH = module;
    lightSubpathHitTriDesc.hitgroup.entryFunctionNameCH = "__closesthit__lightSubpath";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &lightSubpathHitTriDesc, 1, &pgOptions, LOG, &LOG_SIZE,
                                             &lightSubpathHitTrianglePG));

    OptixProgramGroupDesc lightSubpathHitSphereDesc{};
    lightSubpathHitSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    lightSubpathHitSphereDesc.hitgroup.moduleCH = module;
    lightSubpathHitSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__lightSubpath";
    lightSubpathHitSphereDesc.hitgroup.moduleIS = sphereModule;
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &lightSubpathHitSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE,
                                             &lightSubpathHitSpherePG));

    OptixProgramGroupDesc lightSubpathHitSolidSphereDesc{};
    lightSubpathHitSolidSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    lightSubpathHitSolidSphereDesc.hitgroup.moduleCH = module;
    lightSubpathHitSolidSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__lightSubpath";
    lightSubpathHitSolidSphereDesc.hitgroup.moduleIS = module;
    lightSubpathHitSolidSphereDesc.hitgroup.entryFunctionNameIS = "__intersection__sphere_solid";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &lightSubpathHitSolidSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE,
                                             &lightSubpathHitSolidSpherePG));

    // Phase 10 denoiser: raygen-only, never calls optixTrace.
    OptixProgramGroupDesc tonemapRaygenDesc{};
    tonemapRaygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    tonemapRaygenDesc.raygen.module = module;
    tonemapRaygenDesc.raygen.entryFunctionName = "__raygen__tonemap";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &tonemapRaygenDesc, 1, &pgOptions, LOG, &LOG_SIZE, &tonemapRaygenPG));
  }

  void buildPipeline() {
    OptixProgramGroup groups[] = {raygenPG,
                                   missRadiancePG,
                                   missOcclusionPG,
                                   hitTrianglePG,
                                   hitSpherePG,
                                   hitSolidSpherePG,
                                   hitVoxelPG,
                                   hitSdfPG,
                                   hitGsplatPG,
                                   lightSubpathRaygenPG,
                                   lightSubpathMissPG,
                                   lightSubpathHitTrianglePG,
                                   lightSubpathHitSpherePG,
                                   lightSubpathHitSolidSpherePG,
                                   tonemapRaygenPG};
    OptixPipelineLinkOptions linkOptions{};
    // raygen -> radiance hit -> occlusion shadow ray (2), or raygen ->
    // radiance hit -> BDPT-connection occlusion shadow ray (2, same
    // traceOcclusion() call as NEE — see __closesthit__radiance), or
    // light-subpath-raygen -> light-subpath-hit (1, no nested trace) — 2
    // covers every path in this pipeline.
    const uint32_t maxTraceDepth = 2;
    linkOptions.maxTraceDepth = maxTraceDepth;
    OPTIX_CHECK_LOG(optixPipelineCreate(context, &pipelineCompileOptions, &linkOptions, groups,
                                         sizeof(groups) / sizeof(groups[0]), LOG, &LOG_SIZE, &pipeline));

    OptixStackSizes stackSizes{};
    for (auto *g : groups)
      OPTIX_CHECK(optixUtilAccumulateStackSizes(g, &stackSizes, pipeline));
    uint32_t dcFromTraversal, dcFromState, contStack;
    OPTIX_CHECK(optixUtilComputeStackSizes(&stackSizes, maxTraceDepth, 0, 0, &dcFromTraversal, &dcFromState,
                                            &contStack));
    // 2, not 1: single-level instancing means a 2-deep traversable graph
    // (top-level IAS -> per-object GAS).
    OPTIX_CHECK(optixPipelineSetStackSize(pipeline, dcFromTraversal, dcFromState, contStack, 2));
  }

  // Every acceleration structure in this renderer wants the same
  // build/sync/free-temp dance; this is the one place it lives.
  //
  // PREFER_FAST_TRACE by default: each AS is built once at scene load and
  // then traced for the rest of the session, so build time is irrelevant and
  // traversal time is everything (doctrine rung 2). VCM Step 1 has no
  // per-frame AS rebuild at all — the old phase-7 photon GAS (the one
  // FAST_BUILD exception this comment used to describe) is gone along with
  // the rest of that pipeline; __closesthit__radiance walks
  // params.lightVertices as a plain array instead. A per-frame rebuild
  // returns in Step 2, once there's a vertex *merging* query to accelerate.
  //
  // Callers whose closest-hit programs call optixGetTriangleVertexData or
  // optixGetSphereData must pass ALLOW_RANDOM_VERTEX_ACCESS. That is a
  // requirement, not a hint: without it those queries are undefined. It is
  // also what makes the GAS retain a copy of the vertex data, which is why
  // callers can free their input buffers as soon as this returns. It is only
  // meaningful on triangle/sphere GAS builds — not custom primitives, not the
  // IAS — so it is opt-in per call site rather than baked in here.
  OptixTraversableHandle buildAccel(const OptixBuildInput &input, CUdeviceptr &outBuffer,
                                     unsigned int buildFlags = OPTIX_BUILD_FLAG_PREFER_FAST_TRACE) {
    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = buildFlags;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));

    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&outBuffer), sizes.outputSizeInBytes));

    OptixTraversableHandle handle = 0;
    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 outBuffer, sizes.outputSizeInBytes, &handle, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    return handle;
  }

  // Geometry whose shading normal is derived on the fly via
  // optixGetTriangleVertexData / optixGetSphereData (see
  // computeGeometricNormal in pathtracer.cu).
  static constexpr unsigned int kTracedGeometryFlags =
      OPTIX_BUILD_FLAG_PREFER_FAST_TRACE | OPTIX_BUILD_FLAG_ALLOW_RANDOM_VERTEX_ACCESS;

  CUdeviceptr uploadTriangles(const std::vector<float3> &verts) {
    CUdeviceptr d;
    const size_t bytes = verts.size() * sizeof(float3);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d), bytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d), verts.data(), bytes, cudaMemcpyHostToDevice));
    return d;
  }

  SceneObject buildTriangleObject(const std::vector<float3> &verts, HitGroupData material) {
    SceneObject obj;
    obj.kind = GeometryKind::Triangle;
    obj.material = material;

    CUdeviceptr vertexBuffer = uploadTriangles(verts);

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
    input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
    input.triangleArray.vertexStrideInBytes = sizeof(float3);
    input.triangleArray.numVertices = static_cast<unsigned int>(verts.size());
    input.triangleArray.vertexBuffers = &vertexBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.triangleArray.flags = flags;
    input.triangleArray.numSbtRecords = 1;

    obj.gas = buildAccel(input, obj.gasBuffer, kTracedGeometryFlags);
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    return obj;
  }

  SceneObject buildSphereObject(float3 center, float radius, HitGroupData material) {
    SceneObject obj;
    obj.kind = GeometryKind::Sphere;
    obj.material = material;

    CUdeviceptr vertexBuffer, radiusBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&vertexBuffer), sizeof(float3)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(vertexBuffer), &center, sizeof(float3), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&radiusBuffer), sizeof(float)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(radiusBuffer), &radius, sizeof(float), cudaMemcpyHostToDevice));

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_SPHERES;
    input.sphereArray.vertexBuffers = &vertexBuffer;
    input.sphereArray.numVertices = 1;
    input.sphereArray.radiusBuffers = &radiusBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.sphereArray.flags = flags;
    input.sphereArray.numSbtRecords = 1;

    obj.gas = buildAccel(input, obj.gasBuffer, kTracedGeometryFlags);
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    cudaFree(reinterpret_cast<void *>(radiusBuffer));
    return obj;
  }

  // A dielectric sphere as a custom primitive: one AABB feeding the BVH, with
  // the actual centre/radius carried in the SBT record for
  // __intersection__sphere_solid to solve against. Same shape as
  // buildSdfObject() — the AABB only ever feeds the build, so it is freed
  // straight after, unlike the voxel path which re-reads its AABB array at
  // intersection time.
  SceneObject buildSolidSphereObject(float3 center, float radius, HitGroupData material) {
    SceneObject obj;
    obj.kind = GeometryKind::SolidSphere;
    obj.material = material;
    obj.material.sphereCenter = center;
    obj.material.sphereRadius = radius;

    OptixAabb aabb{center.x - radius, center.y - radius, center.z - radius,
                   center.x + radius, center.y + radius, center.z + radius};
    CUdeviceptr aabbBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&aabbBuffer), sizeof(OptixAabb)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(aabbBuffer), &aabb, sizeof(OptixAabb), cudaMemcpyHostToDevice));

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &aabbBuffer;
    input.customPrimitiveArray.numPrimitives = 1;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    obj.gas = buildAccel(input, obj.gasBuffer);
    cudaFree(reinterpret_cast<void *>(aabbBuffer));
    return obj;
  }

  // Adds a rectangular emissive object at the given corner/edges, both as
  // real (camera-visible) geometry and as the analytic params.light used for
  // NEE — shared by the fixed bring-up scene and the GLB-mesh/voxel/sdf
  // scenes, which all need *something* to light the object when there's no
  // environment map active (the two lighting modes aren't blended: an
  // environment supersedes the quad light entirely, see Params::envTex).
  void addLightQuad(float3 corner, float3 v1, float3 v2, float3 emission) {
    if (hasEnvironment)
      return;
    light.corner = corner;
    light.v1 = v1;
    light.v2 = v2;
    light.normal = normalize(cross(v1, v2));
    light.emission = emission;

    HitGroupData lightMat{};
    lightMat.materialType = MATERIAL_LIGHT;
    lightMat.emission = emission;
    objects.push_back(buildTriangleObject(
        {corner, corner + v1, corner + v1 + v2, corner, corner + v1 + v2, corner + v2}, lightMat));
  }

  // Uploads one 8-bit RGBA texture. `srgb` must match how the data is meant
  // to be read: base colour is sRGB-encoded and gets decoded in texture
  // hardware for free, while metallic-roughness and normal maps are linear
  // *data* — decoding those would bend every normal toward +Z and skew
  // roughness, so the flag travels with the texture rather than being
  // assumed here.
  cudaTextureObject_t uploadTexture(const TextureAsset &tex, bool srgb) {
    const cudaChannelFormatDesc desc = cudaCreateChannelDesc<uchar4>();
    cudaArray_t array = nullptr;
    CUDA_CHECK(cudaMallocArray(&array, &desc, tex.width, tex.height));
    CUDA_CHECK(cudaMemcpy2DToArray(array, 0, 0, tex.pixelsRGBA.data(), tex.width * 4, tex.width * 4, tex.height,
                                    cudaMemcpyHostToDevice));
    textureArrays.push_back(array);

    cudaResourceDesc resDesc{};
    resDesc.resType = cudaResourceTypeArray;
    resDesc.res.array.array = array;
    cudaTextureDesc texDesc{};
    texDesc.addressMode[0] = cudaAddressModeWrap;
    texDesc.addressMode[1] = cudaAddressModeWrap;
    texDesc.filterMode = cudaFilterModeLinear;
    texDesc.readMode = cudaReadModeNormalizedFloat;
    texDesc.normalizedCoords = 1;
    texDesc.sRGB = srgb ? 1 : 0;
    cudaTextureObject_t obj = 0;
    CUDA_CHECK(cudaCreateTextureObject(&obj, &resDesc, &texDesc, nullptr));
    textureObjects.push_back(obj);
    return obj;
  }

  template <typename T> CUdeviceptr uploadVector(const std::vector<T> &v) {
    if (v.empty())
      return 0;
    CUdeviceptr d = 0;
    const size_t bytes = v.size() * sizeof(T);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d), bytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d), v.data(), bytes, cudaMemcpyHostToDevice));
    return d;
  }

  SceneObject buildMeshObject(const MeshAsset &mesh) {
    SceneObject obj;
    obj.kind = GeometryKind::Triangle;
    obj.material.materialType = MATERIAL_TEXTURED_DIFFUSE;

    std::vector<float3> positions(mesh.positions.size());
    for (size_t i = 0; i < mesh.positions.size(); ++i)
      positions[i] = toFloat3(mesh.positions[i]);

    std::vector<float3> normals(mesh.normals.size());
    for (size_t i = 0; i < mesh.normals.size(); ++i)
      normals[i] = toFloat3(mesh.normals[i]);
    meshNormals = uploadVector(normals);
    obj.material.normals = reinterpret_cast<float3 *>(meshNormals);

    std::vector<float2> uvs(mesh.uvs.size());
    for (size_t i = 0; i < mesh.uvs.size(); ++i)
      uvs[i] = make_float2(mesh.uvs[i].x, mesh.uvs[i].y);
    meshUvs = uploadVector(uvs);
    obj.material.uvs = reinterpret_cast<float2 *>(meshUvs);

    std::vector<float4> tangents(mesh.tangents.size());
    for (size_t i = 0; i < mesh.tangents.size(); ++i)
      tangents[i] = make_float4(mesh.tangents[i].x, mesh.tangents[i].y, mesh.tangents[i].z, mesh.tangents[i].w);
    meshTangents = uploadVector(tangents);
    obj.material.tangents = reinterpret_cast<float4 *>(meshTangents);

    meshTriangleMaterial = uploadVector(mesh.triangleMaterial);
    obj.material.triangleMaterial = reinterpret_cast<unsigned int *>(meshTriangleMaterial);

    // One texture object per TextureAsset, then materials reference them by
    // index. The loader already de-duplicates images, so this uploads each
    // one exactly once no matter how many materials share it.
    std::vector<cudaTextureObject_t> texObjects(mesh.textures.size(), 0);
    for (size_t i = 0; i < mesh.textures.size(); ++i)
      if (mesh.textures[i].width > 0 && mesh.textures[i].height > 0)
        texObjects[i] = uploadTexture(mesh.textures[i], mesh.textures[i].srgb);

    auto texOrZero = [&](int index) -> cudaTextureObject_t {
      return index >= 0 && index < static_cast<int>(texObjects.size()) ? texObjects[index] : 0;
    };
    std::vector<GpuMaterial> gpuMaterials(mesh.materials.size());
    for (size_t i = 0; i < mesh.materials.size(); ++i) {
      const MaterialAsset &m = mesh.materials[i];
      GpuMaterial &g = gpuMaterials[i];
      g.baseColorFactor = toFloat3(m.baseColorFactor);
      g.metallic = m.metallic;
      g.roughness = m.roughness;
      g.normalScale = m.normalScale;
      g.baseColorTex = texOrZero(m.baseColorTexture);
      g.metallicRoughnessTex = texOrZero(m.metallicRoughnessTexture);
      g.normalTex = texOrZero(m.normalTexture);
      g.transmission = m.transmission;
      g.ior = m.ior;
      g.attenuationColor = toFloat3(m.attenuationColor);
      g.attenuationDistance = m.attenuationDistance;
    }
    meshMaterials = uploadVector(gpuMaterials);
    obj.material.materials = reinterpret_cast<GpuMaterial *>(meshMaterials);

    CUdeviceptr vertexBuffer = uploadTriangles(positions);
    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
    input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
    input.triangleArray.vertexStrideInBytes = sizeof(float3);
    input.triangleArray.numVertices = static_cast<unsigned int>(positions.size());
    input.triangleArray.vertexBuffers = &vertexBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.triangleArray.flags = flags;
    input.triangleArray.numSbtRecords = 1;

    // Random vertex access as well: __closesthit__lightSubpath derives its
    // normal via optixGetTriangleVertexData, and light subpaths now run for
    // loaded-mesh scenes.
    obj.gas = buildAccel(input, obj.gasBuffer, kTracedGeometryFlags);
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    return obj;
  }

  SceneObject buildVoxelObject(const VoxelGrid &grid) {
    SceneObject obj;
    obj.kind = GeometryKind::Voxel;
    obj.material.materialType = MATERIAL_VOXEL;

    std::vector<OptixAabb> aabbs(grid.cells.size());
    for (size_t i = 0; i < grid.cells.size(); ++i) {
      const glm::vec3 mn = grid.cellMin(grid.cells[i]);
      const glm::vec3 mx = grid.cellMax(grid.cells[i]);
      aabbs[i] = OptixAabb{mn.x, mn.y, mn.z, mx.x, mx.y, mx.z};
    }
    const size_t aabbBytes = aabbs.size() * sizeof(OptixAabb);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&voxelAabbBuffer), aabbBytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(voxelAabbBuffer), aabbs.data(), aabbBytes, cudaMemcpyHostToDevice));
    obj.material.voxelAabbs = reinterpret_cast<OptixAabb *>(voxelAabbBuffer);

    std::vector<float3> colors(grid.colors.size());
    for (size_t i = 0; i < grid.colors.size(); ++i)
      colors[i] = toFloat3(grid.colors[i]);
    const size_t colorBytes = colors.size() * sizeof(float3);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&voxelColorBuffer), colorBytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(voxelColorBuffer), colors.data(), colorBytes, cudaMemcpyHostToDevice));
    obj.material.voxelColors = reinterpret_cast<float3 *>(voxelColorBuffer);

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &voxelAabbBuffer;
    input.customPrimitiveArray.numPrimitives = static_cast<unsigned int>(aabbs.size());
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    // Custom primitives: no built-in vertex data to query, so plain fast-trace.
    obj.gas = buildAccel(input, obj.gasBuffer);
    return obj;
  }

  // Single custom primitive covering the whole SDF grid's bounding box —
  // unlike voxels there's no sparse-cell array, just one continuous field
  // that __intersection__sdf sphere-traces through.
  SceneObject buildSdfObject(const SdfGrid &grid) {
    SceneObject obj;
    obj.kind = GeometryKind::Sdf;
    obj.material.materialType = MATERIAL_SDF;
    obj.material.albedo = toFloat3(grid.tintColor);
    obj.material.sdfOrigin = toFloat3(grid.origin);
    obj.material.sdfVoxelSize = grid.voxelSize;
    obj.material.sdfNx = grid.nx;
    obj.material.sdfNy = grid.ny;
    obj.material.sdfNz = grid.nz;

    const size_t bytes = grid.distances.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&sdfDistanceBuffer), bytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(sdfDistanceBuffer), grid.distances.data(), bytes, cudaMemcpyHostToDevice));
    obj.material.sdfDistances = reinterpret_cast<float *>(sdfDistanceBuffer);

    const glm::vec3 boundsMax = grid.boundsMax();
    OptixAabb aabb{grid.origin.x, grid.origin.y, grid.origin.z, boundsMax.x, boundsMax.y, boundsMax.z};
    CUdeviceptr aabbBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&aabbBuffer), sizeof(OptixAabb)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(aabbBuffer), &aabb, sizeof(OptixAabb), cudaMemcpyHostToDevice));

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &aabbBuffer;
    input.customPrimitiveArray.numPrimitives = 1;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    obj.gas = buildAccel(input, obj.gasBuffer);
    cudaFree(reinterpret_cast<void *>(aabbBuffer)); // only fed the build, not read at intersection time (unlike voxels)
    return obj;
  }

  // One custom AABB per splat (3-sigma ellipsoid bound, see
  // convert/gsplat_bounds.h) feeds the BVH build; __intersection__gsplat and
  // __anyhit__gsplat re-derive the actual ellipsoid/Gaussian directly from
  // the position/scale/rotation/opacity/color arrays below rather than
  // re-reading the AABB, so — like buildSdfObject/buildSolidSphereObject,
  // unlike buildVoxelObject — the AABB buffer only needs to survive the
  // build.
  SceneObject buildSplatObject(const GsplatAsset &splats) {
    SceneObject obj;
    obj.kind = GeometryKind::Gsplat;
    obj.material.materialType = MATERIAL_GSPLAT;

    std::vector<OptixAabb> aabbs(splats.count());
    for (size_t i = 0; i < splats.count(); ++i) {
      const auto [lo, hi] = computeSplatAabb(splats.positions[i], splats.scales[i], splats.rotations[i]);
      aabbs[i] = OptixAabb{lo.x, lo.y, lo.z, hi.x, hi.y, hi.z};
    }
    CUdeviceptr aabbBuffer;
    const size_t aabbBytes = aabbs.size() * sizeof(OptixAabb);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&aabbBuffer), aabbBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(aabbBuffer), aabbs.data(), aabbBytes, cudaMemcpyHostToDevice));

    std::vector<float3> positions(splats.count());
    std::vector<float3> scales(splats.count());
    std::vector<float4> rotations(splats.count());
    std::vector<float3> colors(splats.count());
    for (size_t i = 0; i < splats.count(); ++i) {
      positions[i] = toFloat3(splats.positions[i]);
      scales[i] = toFloat3(splats.scales[i]);
      rotations[i] = make_float4(splats.rotations[i].x, splats.rotations[i].y, splats.rotations[i].z,
                                  splats.rotations[i].w);
      colors[i] = toFloat3(splats.colorDC[i]);
    }
    splatPositionBuffer = uploadVector(positions);
    obj.material.splatPositions = reinterpret_cast<float3 *>(splatPositionBuffer);
    splatScaleBuffer = uploadVector(scales);
    obj.material.splatScales = reinterpret_cast<float3 *>(splatScaleBuffer);
    splatRotationBuffer = uploadVector(rotations);
    obj.material.splatRotations = reinterpret_cast<float4 *>(splatRotationBuffer);
    splatOpacityBuffer = uploadVector(splats.opacity);
    obj.material.splatOpacity = reinterpret_cast<float *>(splatOpacityBuffer);
    splatColorBuffer = uploadVector(colors);
    obj.material.splatColors = reinterpret_cast<float3 *>(splatColorBuffer);

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &aabbBuffer;
    input.customPrimitiveArray.numPrimitives = static_cast<unsigned int>(aabbs.size());
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    obj.gas = buildAccel(input, obj.gasBuffer);
    cudaFree(reinterpret_cast<void *>(aabbBuffer));
    return obj;
  }

  void buildSplatScene(const GsplatAsset &splats) {
    objects.push_back(buildSplatObject(splats));
    boundsCenter = splats.boundsCenter();
    boundsRadius = std::max(splats.boundsRadius(), 1e-3f);
    addGroundPlane(boundsCenter, boundsRadius, splats.boundsMin.y);
    addBoundsKeyLight(boundsCenter, boundsRadius);
    // No light-subpath eligibility, same reasoning as voxel/SDF scenes: flat
    // diffuse only, no per-primitive material to test for a specular/
    // transmissive lobe, and eye-path-only per the VCM plan's scope boundary
    // regardless (see enableLightSubpaths' other doc comments).
  }

  void buildFixedTestScene() {
    HitGroupData groundMat{};
    groundMat.materialType = MATERIAL_DIFFUSE;
    groundMat.albedo = make_float3(0.72f, 0.72f, 0.7f);
    objects.push_back(buildTriangleObject(
        {
            make_float3(-3, -1, -3),
            make_float3(3, -1, -3),
            make_float3(3, -1, 3),
            make_float3(-3, -1, -3),
            make_float3(3, -1, 3),
            make_float3(-3, -1, 3),
        },
        groundMat));

    addLightQuad(make_float3(-0.6f, 2.9f, -0.6f), make_float3(1.2f, 0, 0), make_float3(0, 0, 1.2f),
                 make_float3(15.0f, 15.0f, 13.0f));

    HitGroupData diffuseMat{};
    diffuseMat.materialType = MATERIAL_DIFFUSE;
    diffuseMat.albedo = make_float3(0.75f, 0.22f, 0.2f);
    objects.push_back(buildSphereObject(make_float3(-1.2f, -0.3f, 0.0f), 0.7f, diffuseMat));

    HitGroupData mirrorMat{};
    mirrorMat.materialType = MATERIAL_MIRROR;
    mirrorMat.albedo = make_float3(0.9f, 0.9f, 0.92f);
    objects.push_back(buildSphereObject(make_float3(0.5f, -0.3f, 0.9f), 0.7f, mirrorMat));

    HitGroupData glassMat{};
    glassMat.materialType = MATERIAL_GLASS;
    glassMat.albedo = make_float3(1.0f, 1.0f, 1.0f);
    glassMat.ior = 1.5f;
    // Absorption per unit distance, so the 1.2-wide centre of the sphere
    // reads distinctly deeper than its thin rim. Red is absorbed hardest,
    // giving the cool blue-green of thick cast glass. Tuned by eye, which is
    // the sanctioned way here — this is an artist control (doctrine rung 1),
    // not a measured material.
    glassMat.extinction = make_float3(0.85f, 0.32f, 0.22f);
    // Floating above the plane (not resting on it) on purpose: refracted
    // rays need room to converge before hitting a receiving surface, or the
    // caustic never has a chance to focus — standard practice for a
    // glass-caustic demo scene, not a physical-plausibility slip.
    objects.push_back(buildSolidSphereObject(make_float3(1.4f, 0.5f, -0.6f), 0.6f, glassMat));

    boundsCenter = glm::vec3(0.0f, 0.2f, 0.0f);
    boundsRadius = 3.0f;

    // Light subpaths only make sense here: this is the only scene with
    // specular (mirror/glass) objects for a subpath to bounce through en
    // route to a connectable diffuse vertex — mesh/voxel/SDF scenes are
    // always MATERIAL_TEXTURED_DIFFUSE/VOXEL/SDF, and voxel/SDF stay
    // eye-path-only per the VCM plan's scope boundary regardless.
    //
    // Not gated on !hasEnvironment: light-subpath emission follows whichever
    // lighting mode NEE is using (see emitFromEnvironment in pathtracer.cu),
    // the same way NEE already treats the two as alternatives, not a reason
    // to drop a feature.
    enableLightSubpaths = true;
  }

  // A neutral plane just under the object, so it has something to cast a
  // contact shadow onto and bounce light off. Sized from the bounding sphere
  // so it reads as "ground" rather than "a slab" at any asset scale, and
  // dropped a hair below the actual minimum so coplanar bottom faces don't
  // z-fight with it.
  //
  // 1.4x radius, not the 6x this originally shipped at. This first shipped
  // sized as "the ground for the whole scene" (6x), which put its hard,
  // perfectly flat silhouette edge well inside the frame at the camera
  // distances OrbitCamera::frame actually uses (~1.15x boundsRadius) — under
  // an HDRI, which already bakes in its own ground and horizon, that edge
  // read as a visibly synthetic seam rather than as ground, and under the
  // noon preset's harsh sun it blew out to pure white and ate most of the
  // frame (confirmed by rendering under ITALY_TONEMAP=clamp). 1.4x is sized
  // to be a *contact-shadow catcher*, not a scene floor: just enough plane
  // for the object's own shadow to land on, small enough that its edge stays
  // near the object instead of cutting across the middle of the frame.
  void addGroundPlane(const glm::vec3 &center, float radius, float floorY) {
    // Also skipped under an environment map, same reasoning as
    // addLightQuad(): an HDRI already bakes in its own ground, horizon, and
    // GI-driven contact darkening under the object. A separate flat grey
    // plane can only disagree with it — measured, not assumed: it read as a
    // visibly synthetic hard-edged card, wrong hue against a warm desert
    // HDRI, that got no better by resizing or darkening it (tried both).
    // Real fix would be a proper alpha shadow-catcher (render receive-shadow
    // difference only, composite over the env) — future work, not this
    // pass's scope. Kept for the no-environment quad-light case, where
    // there is no ground at all otherwise.
    if (!wantGroundPlane || hasEnvironment)
      return;
    const float r = radius * 1.4f;
    const float y = floorY - radius * 1e-3f;
    HitGroupData mat{};
    mat.materialType = MATERIAL_DIFFUSE;
    // Mid-grey: bright enough to catch bounce light and show a shadow, dark
    // enough not to blow out under a daylight HDRI. Still can clip under a
    // very bright preset (noon) at default exposure — that's exposure's job
    // to tame, same as it would be for a real ground plane in direct sun.
    mat.albedo = make_float3(0.45f, 0.45f, 0.45f);
    const float3 c = toFloat3(center);
    objects.push_back(buildTriangleObject(
        {
            make_float3(c.x - r, y, c.z - r), make_float3(c.x + r, y, c.z - r), make_float3(c.x + r, y, c.z + r),
            make_float3(c.x - r, y, c.z - r), make_float3(c.x + r, y, c.z + r), make_float3(c.x - r, y, c.z + r),
        },
        mat));
  }

  // Key light sized/positioned relative to a bounding sphere so it's sensible
  // regardless of the loaded asset's own scale — shared by the mesh and
  // voxel scenes, which both need *something* to be lit by (no HDRI yet).
  void addBoundsKeyLight(const glm::vec3 &center, float radius) {
    const float3 c = toFloat3(center);
    const float r = radius;
    addLightQuad(make_float3(c.x - r, c.y + r * 2.2f, c.z - r), make_float3(r * 2.0f, 0, 0),
                 make_float3(0, 0, r * 2.0f), make_float3(20.0f, 20.0f, 18.0f));
  }

  void buildMeshScene(const MeshAsset &mesh) {
    objects.push_back(buildMeshObject(mesh));
    boundsCenter = mesh.boundsCenter();
    boundsRadius = std::max(mesh.boundsRadius(), 1e-3f);
    addGroundPlane(boundsCenter, boundsRadius, mesh.boundsMin.y);
    addBoundsKeyLight(boundsCenter, boundsRadius);

    // Same eligibility test __closesthit__lightSubpath's MATERIAL_TEXTURED_
    // DIFFUSE branch uses (KHR_materials_transmission, or a mirror-like
    // metallic/roughness combo) — checked here purely to decide whether it's
    // worth building the light-subpath pipeline at all, not to duplicate its
    // logic.
    for (const MaterialAsset &m : mesh.materials) {
      if (m.transmission > 0.0f || (m.metallic > kCausticMirrorMetallic && m.roughness < kCausticMirrorRoughness)) {
        enableLightSubpaths = true;
        break;
      }
    }
  }

  void buildVoxelScene(const VoxelGrid &grid) {
    objects.push_back(buildVoxelObject(grid));
    glm::vec3 mn(1e30f), mx(-1e30f);
    for (const glm::ivec3 &c : grid.cells) {
      mn = glm::min(mn, grid.cellMin(c));
      mx = glm::max(mx, grid.cellMax(c));
    }
    boundsCenter = (mn + mx) * 0.5f;
    boundsRadius = std::max(glm::length(mx - mn) * 0.5f, 1e-3f);
    addGroundPlane(boundsCenter, boundsRadius, mn.y);
    addBoundsKeyLight(boundsCenter, boundsRadius);
  }

  void buildSdfScene(const SdfGrid &grid) {
    objects.push_back(buildSdfObject(grid));
    const glm::vec3 mx = grid.boundsMax();
    boundsCenter = (grid.origin + mx) * 0.5f;
    boundsRadius = std::max(glm::length(mx - grid.origin) * 0.5f, 1e-3f);
    addGroundPlane(boundsCenter, boundsRadius, grid.origin.y);
    addBoundsKeyLight(boundsCenter, boundsRadius);
  }

  // Uploads the environment map's pixels (as a bilinear-filtered float
  // texture — HDR data is already linear radiance, no sRGB conversion) and
  // its importance-sampling CDFs as plain device buffers (manual binary
  // search on the device, same "flat buffer, no texture-hardware tricks"
  // choice as the SDF grid — simpler and plenty fast at these sizes).
  void buildEnvironment(const EnvironmentMap &env) {
    hasEnvironment = true;
    envWidth = env.width;
    envHeight = env.height;

    std::vector<float4> rgba(static_cast<size_t>(env.width) * env.height);
    for (size_t i = 0; i < rgba.size(); ++i)
      rgba[i] = make_float4(env.pixels[i * 3 + 0], env.pixels[i * 3 + 1], env.pixels[i * 3 + 2], 1.0f);

    const cudaChannelFormatDesc desc = cudaCreateChannelDesc<float4>();
    CUDA_CHECK(cudaMallocArray(&envArray, &desc, env.width, env.height));
    CUDA_CHECK(cudaMemcpy2DToArray(envArray, 0, 0, rgba.data(), env.width * sizeof(float4), env.width * sizeof(float4),
                                    env.height, cudaMemcpyHostToDevice));
    cudaResourceDesc resDesc{};
    resDesc.resType = cudaResourceTypeArray;
    resDesc.res.array.array = envArray;
    cudaTextureDesc texDesc{};
    texDesc.addressMode[0] = cudaAddressModeWrap;  // u: wraps around the horizon
    texDesc.addressMode[1] = cudaAddressModeClamp; // v: clamp at the poles
    texDesc.filterMode = cudaFilterModeLinear;
    texDesc.readMode = cudaReadModeElementType; // already linear float radiance, no normalization/sRGB
    texDesc.normalizedCoords = 1;
    CUDA_CHECK(cudaCreateTextureObject(&envTexObj, &resDesc, &texDesc, nullptr));

    const size_t marginalBytes = env.marginalCdf.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&envMarginalCdfBuffer), marginalBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(envMarginalCdfBuffer), env.marginalCdf.data(), marginalBytes,
                           cudaMemcpyHostToDevice));

    const size_t conditionalBytes = env.conditionalCdf.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&envConditionalCdfBuffer), conditionalBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(envConditionalCdfBuffer), env.conditionalCdf.data(),
                           conditionalBytes, cudaMemcpyHostToDevice));
  }

  void buildScene(const SceneSource &source) {
    // Must happen before any of the geometry-building calls below: they
    // consult hasEnvironment (via addLightQuad) to decide whether to add a
    // synthetic quad light.
    wantGroundPlane = source.groundPlane;
    if (source.environment)
      buildEnvironment(*source.environment);

    if (source.splats)
      buildSplatScene(*source.splats);
    else if (source.sdf)
      buildSdfScene(*source.sdf);
    else if (source.voxels)
      buildVoxelScene(*source.voxels);
    else if (source.mesh)
      buildMeshScene(*source.mesh);
    else
      buildFixedTestScene();

    buildIAS();

    if (enableLightSubpaths) {
      buildLightSubpathSbt();
      CUDA_CHECK(
          cudaMalloc(reinterpret_cast<void **>(&lightVertexBuffer), sizeof(LightVertex) * kLightVertexCapacity));
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&lightVertexCounterBuffer), sizeof(unsigned int)));
    }
  }

  // A second SBT sharing this same pipeline, used only for the
  // light-subpath-emission launch. optixLaunch's SBT argument is what
  // resolves every trace call's hit-group/miss index for programs invoked
  // *by* that launch (raygen and anything reached from it) — so
  // __raygen__lightSubpath's own optixTrace(params.handle, ...,
  // sbtOffset=<object index>, ...) calls resolve against *this* table,
  // reaching __closesthit__lightSubpath for the same objects that
  // radianceSbt resolves to __closesthit__radiance. That's the whole reason
  // this needs to be a separate table rather than extending radianceSbt: the
  // emission raygen hits the *same* scene instances as the camera raygen,
  // and instance.sbtOffset is baked into the IAS at object-index
  // granularity, not ray-type granularity — a second SBT sidesteps needing
  // to introduce ray-type-multiplexed indexing
  // (sbtOffset*RAY_TYPE_COUNT+rayType) into the already-verified
  // radiance/occlusion indexing at all.
  void buildLightSubpathSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(lightSubpathRaygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));

    MissRecord missRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(lightSubpathMissPG, &missRecord));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_miss), &missRecord, sizeof(missRecord), cudaMemcpyHostToDevice));

    std::vector<HitGroupRecord> hitRecords(objects.size());
    for (size_t i = 0; i < objects.size(); ++i) {
      // Fixed test scene only ever has triangle/sphere objects (see
      // enableLightSubpaths) — no voxel/sdf case to handle here. The solid
      // sphere does need its own entry: it is a custom primitive, so packing
      // it against the triangle program group would leave it with no
      // intersection program at all and the glass would vanish from the
      // light-subpath pass.
      OptixProgramGroup pg = lightSubpathHitTrianglePG;
      if (objects[i].kind == GeometryKind::Sphere)
        pg = lightSubpathHitSpherePG;
      else if (objects[i].kind == GeometryKind::SolidSphere)
        pg = lightSubpathHitSolidSpherePG;
      OPTIX_CHECK(optixSbtRecordPackHeader(pg, &hitRecords[i]));
      hitRecords[i].data = objects[i].material;
    }
    CUdeviceptr d_hit;
    const size_t hitBytes = hitRecords.size() * sizeof(HitGroupRecord);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hit), hitBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hit), hitRecords.data(), hitBytes, cudaMemcpyHostToDevice));

    lightSubpathSbt.raygenRecord = d_rg;
    lightSubpathSbt.missRecordBase = d_miss;
    lightSubpathSbt.missRecordStrideInBytes = sizeof(MissRecord);
    lightSubpathSbt.missRecordCount = 1;
    lightSubpathSbt.hitgroupRecordBase = d_hit;
    lightSubpathSbt.hitgroupRecordStrideInBytes = sizeof(HitGroupRecord);
    lightSubpathSbt.hitgroupRecordCount = static_cast<unsigned int>(hitRecords.size());
  }

  // Emits one pass of light subpaths (the caller must already have uploaded
  // a Params with lightVertices/lightVertexCounter/lightVertexCapacity/
  // lightSubpathBatchSize/light/handle set, for the emission launch itself
  // to read). Returns the number of vertices deposited this pass (clamped to
  // capacity) so the caller can set Params::lightVertexCount for the main
  // eye-path launch that follows. Called once per render() call, same as the
  // old photon pass — see that function for why camera movement doesn't
  // reset any of this (light subpaths are view-independent).
  //
  // Unlike the phase-7 photon pass this replaces, there is no acceleration
  // structure rebuild here: Step 1 has no vertex *merging*, so
  // __closesthit__radiance just iterates params.lightVertices directly (see
  // its doc comment in pathtracer_params.h). Step 2 is what adds a
  // per-frame GAS rebuild over this same buffer for the merge query.
  unsigned int traceLightSubpathPass() {
    CUDA_CHECK(cudaMemsetAsync(reinterpret_cast<void *>(lightVertexCounterBuffer), 0, sizeof(unsigned int), stream));
    OPTIX_CHECK(
        optixLaunch(pipeline, stream, paramsBuffer, sizeof(Params), &lightSubpathSbt, kLightSubpathBatchSize, 1, 1));

    unsigned int deposited = 0;
    CUDA_CHECK(cudaMemcpyAsync(&deposited, reinterpret_cast<void *>(lightVertexCounterBuffer), sizeof(unsigned int),
                               cudaMemcpyDeviceToHost, stream));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    deposited = std::min(deposited, kLightVertexCapacity);
    if (lightSubpathPassIndex < 3 || lightSubpathPassIndex % 64 == 0)
      std::fprintf(stderr, "italy: light-subpath pass %u: %u vertices deposited\n", lightSubpathPassIndex,
                   deposited);
    ++lightSubpathPassIndex;
    totalLightPathsEmitted += kLightSubpathBatchSize;
    return deposited;
  }

  void buildIAS() {
    // Instance acceleration structure over the objects built above.
    std::vector<OptixInstance> instances(objects.size());
    static const float identity[12] = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0};
    for (size_t i = 0; i < objects.size(); ++i) {
      OptixInstance &inst = instances[i];
      std::memset(&inst, 0, sizeof(inst));
      std::memcpy(inst.transform, identity, sizeof(identity));
      inst.instanceId = static_cast<unsigned int>(i);
      inst.visibilityMask = 1;
      inst.sbtOffset = static_cast<unsigned int>(i);
      inst.flags = OPTIX_INSTANCE_FLAG_NONE;
      inst.traversableHandle = objects[i].gas;
    }

    CUdeviceptr instanceBuffer;
    const size_t instBytes = instances.size() * sizeof(OptixInstance);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&instanceBuffer), instBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(instanceBuffer), instances.data(), instBytes,
                           cudaMemcpyHostToDevice));

    OptixBuildInput iasInput{};
    iasInput.type = OPTIX_BUILD_INPUT_TYPE_INSTANCES;
    iasInput.instanceArray.instances = instanceBuffer;
    iasInput.instanceArray.numInstances = static_cast<unsigned int>(instances.size());

    iasHandle = buildAccel(iasInput, iasBuffer);
    cudaFree(reinterpret_cast<void *>(instanceBuffer));
  }

  void buildSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(raygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));

    // Just the two miss programs radiance/occlusion always needed. VCM
    // Step 1 has no third (gather-style) trace from inside
    // __closesthit__radiance — the BDPT connection loop's shadow rays reuse
    // missOcclusionPG via the same traceOcclusion() helper NEE already
    // calls, so there is no separate miss index or SBT-layout variant to
    // carry the way the old phase-7 gather query needed.
    MissRecord missRecords[2]{};
    OPTIX_CHECK(optixSbtRecordPackHeader(missRadiancePG, &missRecords[0]));
    missRecords[0].data.bgColor = make_float3(0.05f, 0.06f, 0.08f);
    OPTIX_CHECK(optixSbtRecordPackHeader(missOcclusionPG, &missRecords[1]));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecords)));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(d_miss), missRecords, sizeof(missRecords), cudaMemcpyHostToDevice));

    std::vector<HitGroupRecord> hitRecords(objects.size());
    for (size_t i = 0; i < objects.size(); ++i) {
      OptixProgramGroup pg;
      switch (objects[i].kind) {
      case GeometryKind::Sphere:
        pg = hitSpherePG;
        break;
      case GeometryKind::SolidSphere:
        pg = hitSolidSpherePG;
        break;
      case GeometryKind::Voxel:
        pg = hitVoxelPG;
        break;
      case GeometryKind::Sdf:
        pg = hitSdfPG;
        break;
      case GeometryKind::Gsplat:
        pg = hitGsplatPG;
        break;
      default:
        pg = hitTrianglePG;
        break;
      }
      OPTIX_CHECK(optixSbtRecordPackHeader(pg, &hitRecords[i]));
      hitRecords[i].data = objects[i].material;
    }
    CUdeviceptr d_hit;
    const size_t hitBytes = hitRecords.size() * sizeof(HitGroupRecord);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hit), hitBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hit), hitRecords.data(), hitBytes, cudaMemcpyHostToDevice));

    sbt.raygenRecord = d_rg;
    sbt.missRecordBase = d_miss;
    sbt.missRecordStrideInBytes = sizeof(MissRecord);
    sbt.missRecordCount = 2;
    sbt.hitgroupRecordBase = d_hit;
    sbt.hitgroupRecordStrideInBytes = sizeof(HitGroupRecord);
    sbt.hitgroupRecordCount = static_cast<unsigned int>(hitRecords.size());
  }

  // Phase 10: the OptiX AI denoiser, color-only (no albedo/normal guide
  // buffers — a real quality improvement but it means threading first-hit
  // G-buffers out of the path tracer too, a natural upgrade rather than
  // required for "wire in the denoiser"). hdrIntensity is left null in
  // OptixDenoiserParams at invoke time (see render()), which the API
  // documents as "autoexposure will be calculated automatically" — good
  // enough for MVP, skips needing a separate optixDenoiserComputeIntensity
  // pass.
  void buildDenoiser(int width, int height) {
    OptixDenoiserOptions options{}; // guideAlbedo=0, guideNormal=0, denoiseAlpha=COPY(0)
    OPTIX_CHECK(optixDenoiserCreate(context, OPTIX_DENOISER_MODEL_KIND_HDR, &options, &denoiser));

    OptixDenoiserSizes sizes{};
    OPTIX_CHECK(optixDenoiserComputeMemoryResources(denoiser, static_cast<unsigned int>(width),
                                                     static_cast<unsigned int>(height), &sizes));
    denoiserStateSize = sizes.stateSizeInBytes;
    denoiserScratchSize = sizes.withoutOverlapScratchSizeInBytes;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&denoiserStateBuffer), denoiserStateSize));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&denoiserScratchBuffer), denoiserScratchSize));
    OPTIX_CHECK(optixDenoiserSetup(denoiser, stream, static_cast<unsigned int>(width),
                                    static_cast<unsigned int>(height), denoiserStateBuffer, denoiserStateSize,
                                    denoiserScratchBuffer, denoiserScratchSize));

    CUDA_CHECK(
        cudaMalloc(reinterpret_cast<void **>(&denoisedBuffer), static_cast<size_t>(width) * height * sizeof(float4)));
  }

  // Third SBT, same reasoning as lightSubpathSbt: __raygen__tonemap runs
  // under its own launch, and needs a raygen record packed for
  // tonemapRaygenPG rather than whatever's in radianceSbt's raygen slot. No
  // hitgroup records at all (not just "unused, harmless" like
  // lightSubpathSbt's radiance-table reuse pattern elsewhere) — this raygen
  // never calls optixTrace, so there is nothing for those tables to ever be
  // consulted for.
  void buildTonemapSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(tonemapRaygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));
    tonemapSbt.raygenRecord = d_rg;

    // OptiX validates that missRecordBase is non-null even though this
    // raygen never calls optixTrace and so can never actually reach a miss
    // program — "no miss table at all" (missRecordCount=0, base=nullptr, as
    // lightSubpathSbt's hitgroup table gets away with) isn't accepted for
    // miss specifically. missOcclusionPG (a real miss program elsewhere in
    // this pipeline, but one this raygen can never reach either way, since
    // it never calls optixTrace) is a convenient already-existing dummy
    // target now that the old gather-query's dedicated no-op miss program is
    // gone along with the rest of that pipeline.
    MissRecord missRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(missOcclusionPG, &missRecord));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_miss), &missRecord, sizeof(missRecord), cudaMemcpyHostToDevice));
    tonemapSbt.missRecordBase = d_miss;
    tonemapSbt.missRecordStrideInBytes = sizeof(MissRecord);
    tonemapSbt.missRecordCount = 1;
  }

  void initGLInterop(int width, int height) {
    const auto &gl = GLBufferFns::get();
    gl.glGenBuffers(1, &pbo);
    gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, pbo);
    gl.glBufferData(GL_PIXEL_UNPACK_BUFFER, static_cast<ptrdiff_t>(width) * height * 4, nullptr, GL_STREAM_DRAW);
    gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0);
    CUDA_CHECK(cudaGraphicsGLRegisterBuffer(&cudaPbo, pbo, cudaGraphicsRegisterFlagsWriteDiscard));

    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&accumBuffer),
                           static_cast<size_t>(width) * height * sizeof(float4)));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&paramsBuffer), sizeof(Params)));
  }
};

OptixRenderer::OptixRenderer(int width, int height, const SceneSource &source)
    : impl_(new Impl()), width_(width), height_(height) {
  impl_->initContext();
  impl_->buildModule();
  impl_->buildProgramGroups();
  impl_->buildPipeline();
  impl_->buildScene(source);
  impl_->buildSbt();
  impl_->buildTonemapSbt();
  impl_->initGLInterop(width, height);
  impl_->buildDenoiser(width, height);

  sceneBoundsCenter_ = impl_->boundsCenter;
  sceneBoundsRadius_ = impl_->boundsRadius;

  glGenTextures(1, &glTexture_);
  glBindTexture(GL_TEXTURE_2D, glTexture_);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);
  glBindTexture(GL_TEXTURE_2D, 0);
}

OptixRenderer::~OptixRenderer() {
  if (glTexture_)
    glDeleteTextures(1, &glTexture_);
  delete impl_;
}

void OptixRenderer::resetAccumulation() { subframeIndex_ = 0; }

void OptixRenderer::render(const OrbitCamera &camera, const RenderSettings &settings) {
  const glm::vec3 eye = camera.position();
  const glm::vec3 target = camera.target();
  const glm::vec3 forward = glm::normalize(target - eye);
  const glm::vec3 worldUp(0, 1, 0);
  const glm::vec3 right = glm::normalize(glm::cross(forward, worldUp));
  const glm::vec3 up = glm::cross(right, forward);
  const float aspect = static_cast<float>(width_) / static_cast<float>(height_);
  const float tanHalfFov = std::tan(camera.fovYRadians * 0.5f);

  Params params{};
  params.subframeIndex = subframeIndex_;
  params.accumBuffer = reinterpret_cast<float4 *>(impl_->accumBuffer);
  params.width = static_cast<unsigned int>(width_);
  params.height = static_cast<unsigned int>(height_);
  params.samplesPerLaunch = settings.samplesPerLaunch;
  params.exposure = settings.exposure;
  params.tonemapOperator = static_cast<unsigned int>(settings.tonemap);
  params.fireflyClamp = settings.fireflyClamp;
  params.aperture = settings.aperture;
  // Default the focal plane to the orbit target, so the thing you framed is
  // the thing in focus without touching a second control.
  params.focusDistance =
      settings.focusDistance > 0.0f ? settings.focusDistance : glm::length(target - eye);
  params.envRotation = settings.envRotation;
  params.sceneBoundsCenter = toFloat3(impl_->boundsCenter);
  params.sceneBoundsRadius = impl_->boundsRadius;
  params.eye = toFloat3(eye);
  params.U = toFloat3(right * tanHalfFov * aspect);
  params.V = toFloat3(up * tanHalfFov);
  params.W = toFloat3(forward);
  params.light = impl_->light;
  params.handle = impl_->iasHandle;
  if (impl_->hasEnvironment) {
    params.envTex = impl_->envTexObj;
    params.envMarginalCdf = reinterpret_cast<float *>(impl_->envMarginalCdfBuffer);
    params.envConditionalCdf = reinterpret_cast<float *>(impl_->envConditionalCdfBuffer);
    params.envWidth = impl_->envWidth;
    params.envHeight = impl_->envHeight;
  }
  // VCM Step 1: run one light-subpath-emission pass before the main launch,
  // so this frame's BDPT connections see it. Not gated on camera movement
  // (unlike accumBuffer/subframeIndex) — light subpaths don't depend on the
  // camera at all, so they keep progressively refreshing regardless of
  // orbiting/panning. Also gated on settings.lightSubpaths, the plan's own
  // A/B verification switch (see RenderSettings::lightSubpaths' doc
  // comment) — lightVertexCount defaults to 0 (Params{} value-init), which
  // makes __closesthit__radiance's connection loop a no-op, the same
  // "reduces to today's NEE-only behaviour" fallback the old
  // photonHandle == 0 convention gave.
  if (impl_->enableLightSubpaths && settings.lightSubpaths) {
    params.lightVertices = reinterpret_cast<LightVertex *>(impl_->lightVertexBuffer);
    params.lightVertexCounter = reinterpret_cast<unsigned int *>(impl_->lightVertexCounterBuffer);
    params.lightVertexCapacity = Impl::kLightVertexCapacity;
    params.lightSubpathBatchSize = Impl::kLightSubpathBatchSize;
    // Must be set *before* this upload, not after — same totalPhotonsEmitted
    // timing lesson the old pipeline learned the hard way (see humans.md's
    // correctness-pass writeup): __raygen__lightSubpath seeds its RNG from
    // this, so it has to be read by the emission launch that
    // traceLightSubpathPass() issues below, not by some later launch.
    params.totalLightPathsEmitted = impl_->totalLightPathsEmitted;
    CUDA_CHECK(cudaMemcpyAsync(reinterpret_cast<void *>(impl_->paramsBuffer), &params, sizeof(Params),
                               cudaMemcpyHostToDevice, impl_->stream));
    const unsigned int deposited = impl_->traceLightSubpathPass();
    params.lightVertexCount = deposited;
    params.totalLightPathsEmitted = impl_->totalLightPathsEmitted; // now includes this pass, for the main launch
  }

  CUDA_CHECK(cudaGraphicsMapResources(1, &impl_->cudaPbo, impl_->stream));
  size_t mappedSize = 0;
  void *devicePtr = nullptr;
  CUDA_CHECK(cudaGraphicsResourceGetMappedPointer(&devicePtr, &mappedSize, impl_->cudaPbo));
  params.frameBuffer = reinterpret_cast<uchar4 *>(devicePtr);
  params.denoiserEnabled = settings.denoise ? 1u : 0u;
  params.denoisedBuffer = reinterpret_cast<float4 *>(impl_->denoisedBuffer);

  CUDA_CHECK(cudaMemcpyAsync(reinterpret_cast<void *>(impl_->paramsBuffer), &params, sizeof(Params),
                             cudaMemcpyHostToDevice, impl_->stream));
  OPTIX_CHECK(optixLaunch(impl_->pipeline, impl_->stream, impl_->paramsBuffer, sizeof(Params), &impl_->sbt, width_,
                           height_, 1));

  if (settings.denoise) {
    // Color-only denoising (no albedo/normal guide layers — see
    // buildDenoiser()'s comment), hdrIntensity left null so the denoiser
    // computes autoexposure internally rather than needing a separate
    // optixDenoiserComputeIntensity pass.
    OptixDenoiserParams denoiserParams{};

    OptixImage2D img{};
    img.width = static_cast<unsigned int>(width_);
    img.height = static_cast<unsigned int>(height_);
    img.rowStrideInBytes = static_cast<unsigned int>(width_) * sizeof(float4);
    img.pixelStrideInBytes = sizeof(float4);
    img.format = OPTIX_PIXEL_FORMAT_FLOAT4;

    OptixImage2D inputImg = img;
    inputImg.data = impl_->accumBuffer;
    OptixImage2D outputImg = img;
    outputImg.data = impl_->denoisedBuffer;

    OptixDenoiserLayer layer{};
    layer.input = inputImg;
    layer.output = outputImg;
    OptixDenoiserGuideLayer guideLayer{}; // all zero: no albedo/normal/flow guides

    OPTIX_CHECK(optixDenoiserInvoke(impl_->denoiser, impl_->stream, &denoiserParams, impl_->denoiserStateBuffer,
                                     impl_->denoiserStateSize, &guideLayer, &layer, 1, 0, 0,
                                     impl_->denoiserScratchBuffer, impl_->denoiserScratchSize));

    // params on the device already has the right frameBuffer/denoisedBuffer/
    // exposure for this — no need to re-upload before this second launch.
    OPTIX_CHECK(optixLaunch(impl_->pipeline, impl_->stream, impl_->paramsBuffer, sizeof(Params), &impl_->tonemapSbt,
                             width_, height_, 1));
  }

  CUDA_CHECK(cudaGraphicsUnmapResources(1, &impl_->cudaPbo, impl_->stream));
  CUDA_CHECK(cudaStreamSynchronize(impl_->stream));

  const auto &gl = GLBufferFns::get();
  gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, impl_->pbo);
  glBindTexture(GL_TEXTURE_2D, glTexture_);
  glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width_, height_, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);
  glBindTexture(GL_TEXTURE_2D, 0);
  gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0);

  ++subframeIndex_;
}

} // namespace italy
