#include "render/optix_renderer.h"

#include <optix.h>
#include <optix_function_table_definition.h>
#include <optix_stack_size.h>
#include <optix_stubs.h>

#include <cuda_gl_interop.h>
#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <sstream>
#include <vector>

#include <sutil/vec_math.h> // float3 operators/cross/normalize — see buildModule() for why this is safe on the host

#include "convert/voxel_grid.h"
#include "render/gl_ext.h"
#include "render/kernels/pathtracer_params.h"
#include "render/optix_check.h"
#include "render_config.h" // generated by CMake: kPathTracerOptixIRPath

namespace italy {
namespace {

float3 toFloat3(const glm::vec3 &v) { return make_float3(v.x, v.y, v.z); }

template <typename T> struct SbtRecord {
  __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
  T data;
};
using RayGenRecord = SbtRecord<RayGenData>;
using MissRecord = SbtRecord<MissData>;
using HitGroupRecord = SbtRecord<HitGroupData>;

std::vector<char> readFile(const char *path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f)
    throw std::runtime_error(std::string("cannot open ") + path);
  const auto size = f.tellg();
  std::vector<char> data(static_cast<size_t>(size));
  f.seekg(0);
  f.read(data.data(), size);
  return data;
}

void contextLogCallback(unsigned int level, const char *tag, const char *message, void *) {
  std::fprintf(stderr, "[optix][%u][%s] %s\n", level, tag, message);
}

enum class GeometryKind { Triangle, Sphere, Voxel, Sdf };

// One static-geometry object in the scene: a GAS (built once) plus the
// material record it contributes to the SBT. `kind` selects which hit-group
// program group (and thus which intersection program) the object's SBT
// record is packed against.
struct SceneObject {
  OptixTraversableHandle gas = 0;
  CUdeviceptr gasBuffer = 0;
  HitGroupData material{};
  GeometryKind kind = GeometryKind::Triangle;
};

} // namespace

struct OptixRenderer::Impl {
  OptixDeviceContext context = nullptr;
  OptixModule module = nullptr;
  OptixModule sphereModule = nullptr;
  OptixPipelineCompileOptions pipelineCompileOptions{};

  OptixProgramGroup raygenPG = nullptr;
  OptixProgramGroup missRadiancePG = nullptr;
  OptixProgramGroup missOcclusionPG = nullptr;
  OptixProgramGroup hitTrianglePG = nullptr;
  OptixProgramGroup hitSpherePG = nullptr;
  OptixProgramGroup hitVoxelPG = nullptr;
  OptixProgramGroup hitSdfPG = nullptr;

  // Phase 7 caustics: a second SBT (photonSbt) sharing this same
  // pipeline/context, used only for the photon-emission launch — see
  // buildPhotonPipeline()'s comment for why a second SBT rather than
  // ray-type-multiplexing the existing one. gatherHitPG/gatherMissPG,
  // though, extend the *main* radianceSbt directly (the gather trace is
  // issued from inside __closesthit__radiance, which runs under
  // radianceSbt's binding — see the Params::gatherHitSbtOffset comment).
  OptixProgramGroup photonRaygenPG = nullptr;
  OptixProgramGroup photonMissPG = nullptr;
  OptixProgramGroup photonHitTrianglePG = nullptr;
  OptixProgramGroup photonHitSpherePG = nullptr;
  OptixProgramGroup gatherHitPG = nullptr;
  OptixProgramGroup gatherMissPG = nullptr;

  // Phase 10 denoiser: __raygen__tonemap is a third raygen-only launch (its
  // own minimal SBT, no miss/hitgroup records — it never calls optixTrace)
  // that reads the denoiser's output into the display buffer. Same "reuse
  // the existing module/pipeline instead of a new CUDA compilation unit"
  // reasoning as photon emission's second SBT.
  OptixProgramGroup tonemapRaygenPG = nullptr;
  OptixShaderBindingTable tonemapSbt{};
  OptixDenoiser denoiser = nullptr;
  CUdeviceptr denoiserStateBuffer = 0;
  size_t denoiserStateSize = 0;
  CUdeviceptr denoiserScratchBuffer = 0;
  size_t denoiserScratchSize = 0;
  CUdeviceptr denoisedBuffer = 0; // float4 * width*height

  OptixPipeline pipeline = nullptr;

  std::vector<SceneObject> objects;
  OptixTraversableHandle iasHandle = 0;
  CUdeviceptr iasBuffer = 0;

  OptixShaderBindingTable sbt{};

  CUstream stream = nullptr;
  CUdeviceptr accumBuffer = 0; // float4 * width*height
  CUdeviceptr paramsBuffer = 0;

  // GL/CUDA interop: CUDA writes the tonemapped frame directly into a mapped
  // pixel-unpack buffer; glTexSubImage2D uploads it from there with no extra
  // device-to-host round trip.
  unsigned int pbo = 0;
  cudaGraphicsResource *cudaPbo = nullptr;

  QuadLight light{};
  glm::vec3 boundsCenter{0.0f};
  float boundsRadius = 3.0f;

  // Device buffers backing a MATERIAL_TEXTURED_DIFFUSE object's per-vertex
  // attributes and optional base-color texture — freed in destroy().
  CUdeviceptr meshNormals = 0;
  CUdeviceptr meshUvs = 0;
  cudaArray_t baseColorArray = nullptr;
  cudaTextureObject_t baseColorTexObj = 0;

  // Device buffers backing a MATERIAL_VOXEL object's per-primitive AABBs
  // (also feeds __intersection__voxel) and baked colors — freed in destroy().
  CUdeviceptr voxelAabbBuffer = 0;
  CUdeviceptr voxelColorBuffer = 0;

  // Device buffer backing a MATERIAL_SDF object's dense distance field —
  // freed in destroy().
  CUdeviceptr sdfDistanceBuffer = 0;

  // Environment/HDRI lighting (phase 6) — freed in destroy(). hasEnvironment
  // gates whether buildFixedTestScene/buildMeshScene/etc add a quad light at
  // all (see addBoundsKeyLight): the two lighting modes aren't blended.
  bool hasEnvironment = false;
  cudaArray_t envArray = nullptr;
  cudaTextureObject_t envTexObj = 0;
  CUdeviceptr envMarginalCdfBuffer = 0;
  CUdeviceptr envConditionalCdfBuffer = 0;
  int envWidth = 0;
  int envHeight = 0;

  // Caustics (phase 7) — only built for the fixed test scene (the only one
  // with specular objects to seed a caustic from) and only when there's no
  // environment map (photon emission samples params.light, which is unset
  // when hasEnvironment). Global-radius progressive photon mapping — see
  // Params::photonHandle's doc comment for which published variant this is.
  bool enablePhotonMapping = false;
  static constexpr unsigned int kPhotonBatchSize = 1u << 16; // 65536 photons/pass
  static constexpr unsigned int kPhotonCapacity = 1u << 18;  // generous headroom over the batch size
  static constexpr float kPpmAlpha = 0.7f;                   // standard PPM radius-decay constant
  OptixShaderBindingTable photonSbt{};
  CUdeviceptr photonBuffer = 0;      // Photon[kPhotonCapacity]
  CUdeviceptr photonCounterBuffer = 0; // single atomic uint
  CUdeviceptr photonGasBuffer = 0;
  CUdeviceptr photonGasVertexBuffer = 0; // kept alive across rebuilds — see buildPhotonMap()
  CUdeviceptr photonGasRadiusBuffer = 0;
  OptixTraversableHandle photonGasHandle = 0;
  unsigned int photonPassIndex = 0;
  float photonRadius = 0.0f;
  unsigned int totalPhotonsEmitted = 0;
  unsigned int gatherHitSbtOffset = 0;

  ~Impl() { destroy(); }

  void destroy() {
    if (baseColorTexObj)
      cudaDestroyTextureObject(baseColorTexObj);
    if (baseColorArray)
      cudaFreeArray(baseColorArray);
    if (meshNormals)
      cudaFree(reinterpret_cast<void *>(meshNormals));
    if (meshUvs)
      cudaFree(reinterpret_cast<void *>(meshUvs));
    if (voxelAabbBuffer)
      cudaFree(reinterpret_cast<void *>(voxelAabbBuffer));
    if (voxelColorBuffer)
      cudaFree(reinterpret_cast<void *>(voxelColorBuffer));
    if (sdfDistanceBuffer)
      cudaFree(reinterpret_cast<void *>(sdfDistanceBuffer));
    if (envTexObj)
      cudaDestroyTextureObject(envTexObj);
    if (envArray)
      cudaFreeArray(envArray);
    if (envMarginalCdfBuffer)
      cudaFree(reinterpret_cast<void *>(envMarginalCdfBuffer));
    if (envConditionalCdfBuffer)
      cudaFree(reinterpret_cast<void *>(envConditionalCdfBuffer));
    if (photonBuffer)
      cudaFree(reinterpret_cast<void *>(photonBuffer));
    if (photonCounterBuffer)
      cudaFree(reinterpret_cast<void *>(photonCounterBuffer));
    if (photonGasBuffer)
      cudaFree(reinterpret_cast<void *>(photonGasBuffer));
    if (photonGasVertexBuffer)
      cudaFree(reinterpret_cast<void *>(photonGasVertexBuffer));
    if (photonGasRadiusBuffer)
      cudaFree(reinterpret_cast<void *>(photonGasRadiusBuffer));
    if (photonSbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(photonSbt.raygenRecord));
    if (photonSbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(photonSbt.missRecordBase));
    if (photonSbt.hitgroupRecordBase)
      cudaFree(reinterpret_cast<void *>(photonSbt.hitgroupRecordBase));
    if (tonemapSbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(tonemapSbt.raygenRecord));
    if (tonemapSbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(tonemapSbt.missRecordBase));
    if (denoisedBuffer)
      cudaFree(reinterpret_cast<void *>(denoisedBuffer));
    if (denoiserStateBuffer)
      cudaFree(reinterpret_cast<void *>(denoiserStateBuffer));
    if (denoiserScratchBuffer)
      cudaFree(reinterpret_cast<void *>(denoiserScratchBuffer));
    if (denoiser)
      optixDenoiserDestroy(denoiser);
    if (paramsBuffer)
      cudaFree(reinterpret_cast<void *>(paramsBuffer));
    if (accumBuffer)
      cudaFree(reinterpret_cast<void *>(accumBuffer));
    if (sbt.raygenRecord)
      cudaFree(reinterpret_cast<void *>(sbt.raygenRecord));
    if (sbt.missRecordBase)
      cudaFree(reinterpret_cast<void *>(sbt.missRecordBase));
    if (sbt.hitgroupRecordBase)
      cudaFree(reinterpret_cast<void *>(sbt.hitgroupRecordBase));
    if (iasBuffer)
      cudaFree(reinterpret_cast<void *>(iasBuffer));
    for (auto &obj : objects)
      if (obj.gasBuffer)
        cudaFree(reinterpret_cast<void *>(obj.gasBuffer));
    if (cudaPbo)
      cudaGraphicsUnregisterResource(cudaPbo);
    if (pbo)
      GLBufferFns::get().glDeleteBuffers(1, &pbo);
    if (pipeline)
      optixPipelineDestroy(pipeline);
    if (tonemapRaygenPG)
      optixProgramGroupDestroy(tonemapRaygenPG);
    if (gatherMissPG)
      optixProgramGroupDestroy(gatherMissPG);
    if (gatherHitPG)
      optixProgramGroupDestroy(gatherHitPG);
    if (photonHitSpherePG)
      optixProgramGroupDestroy(photonHitSpherePG);
    if (photonHitTrianglePG)
      optixProgramGroupDestroy(photonHitTrianglePG);
    if (photonMissPG)
      optixProgramGroupDestroy(photonMissPG);
    if (photonRaygenPG)
      optixProgramGroupDestroy(photonRaygenPG);
    if (hitSdfPG)
      optixProgramGroupDestroy(hitSdfPG);
    if (hitVoxelPG)
      optixProgramGroupDestroy(hitVoxelPG);
    if (hitSpherePG)
      optixProgramGroupDestroy(hitSpherePG);
    if (hitTrianglePG)
      optixProgramGroupDestroy(hitTrianglePG);
    if (missOcclusionPG)
      optixProgramGroupDestroy(missOcclusionPG);
    if (missRadiancePG)
      optixProgramGroupDestroy(missRadiancePG);
    if (raygenPG)
      optixProgramGroupDestroy(raygenPG);
    if (sphereModule)
      optixModuleDestroy(sphereModule);
    if (module)
      optixModuleDestroy(module);
    if (context)
      optixDeviceContextDestroy(context);
  }

  void initContext() {
    CUDA_CHECK(cudaFree(nullptr)); // establish the primary CUDA context
    OPTIX_CHECK(optixInit());
    OptixDeviceContextOptions options{};
    options.logCallbackFunction = &contextLogCallback;
    options.logCallbackLevel = 3;
    OPTIX_CHECK(optixDeviceContextCreate(nullptr, &options, &context));
    CUDA_CHECK(cudaStreamCreate(&stream));
  }

  void buildModule() {
    pipelineCompileOptions.usesMotionBlur = false;
    pipelineCompileOptions.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_LEVEL_INSTANCING;
    pipelineCompileOptions.numPayloadValues = 19;
    pipelineCompileOptions.numAttributeValues = 2;
    pipelineCompileOptions.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    pipelineCompileOptions.pipelineLaunchParamsVariableName = "params";
    pipelineCompileOptions.usesPrimitiveTypeFlags =
        OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE | OPTIX_PRIMITIVE_TYPE_FLAGS_SPHERE | OPTIX_PRIMITIVE_TYPE_FLAGS_CUSTOM;

    OptixModuleCompileOptions moduleOptions{};
    moduleOptions.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_3;
    moduleOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;

    const std::vector<char> ir = readFile(kPathTracerOptixIRPath);
    OPTIX_CHECK_LOG(optixModuleCreate(context, &moduleOptions, &pipelineCompileOptions, ir.data(), ir.size(), LOG,
                                       &LOG_SIZE, &module));

    OptixBuiltinISOptions sphereOpts{};
    sphereOpts.usesMotionBlur = false;
    sphereOpts.builtinISModuleType = OPTIX_PRIMITIVE_TYPE_SPHERE;
    OPTIX_CHECK_LOG(
        optixBuiltinISModuleGet(context, &moduleOptions, &pipelineCompileOptions, &sphereOpts, &sphereModule));
  }

  void buildProgramGroups() {
    OptixProgramGroupOptions pgOptions{};

    OptixProgramGroupDesc raygenDesc{};
    raygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    raygenDesc.raygen.module = module;
    raygenDesc.raygen.entryFunctionName = "__raygen__rg";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &raygenDesc, 1, &pgOptions, LOG, &LOG_SIZE, &raygenPG));

    OptixProgramGroupDesc missRadDesc{};
    missRadDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    missRadDesc.miss.module = module;
    missRadDesc.miss.entryFunctionName = "__miss__radiance";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &missRadDesc, 1, &pgOptions, LOG, &LOG_SIZE, &missRadiancePG));

    OptixProgramGroupDesc missOccDesc{};
    missOccDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    missOccDesc.miss.module = module;
    missOccDesc.miss.entryFunctionName = "__miss__occlusion";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &missOccDesc, 1, &pgOptions, LOG, &LOG_SIZE, &missOcclusionPG));

    OptixProgramGroupDesc hitTriDesc{};
    hitTriDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitTriDesc.hitgroup.moduleCH = module;
    hitTriDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    // Triangle intersection is built into OptiX; no IS module needed.
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitTriDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitTrianglePG));

    OptixProgramGroupDesc hitSphereDesc{};
    hitSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitSphereDesc.hitgroup.moduleCH = module;
    hitSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitSphereDesc.hitgroup.moduleIS = sphereModule;
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitSpherePG));

    OptixProgramGroupDesc hitVoxelDesc{};
    hitVoxelDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitVoxelDesc.hitgroup.moduleCH = module;
    hitVoxelDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    // Custom (non-builtin) primitive — our own intersection program, same
    // module as everything else since it's compiled from pathtracer.cu too.
    hitVoxelDesc.hitgroup.moduleIS = module;
    hitVoxelDesc.hitgroup.entryFunctionNameIS = "__intersection__voxel";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitVoxelDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitVoxelPG));

    OptixProgramGroupDesc hitSdfDesc{};
    hitSdfDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    hitSdfDesc.hitgroup.moduleCH = module;
    hitSdfDesc.hitgroup.entryFunctionNameCH = "__closesthit__radiance";
    hitSdfDesc.hitgroup.moduleIS = module;
    hitSdfDesc.hitgroup.entryFunctionNameIS = "__intersection__sdf";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hitSdfDesc, 1, &pgOptions, LOG, &LOG_SIZE, &hitSdfPG));

    // Phase 7 caustics: photon emission (own raygen/miss, reuses the
    // triangle/sphere IS modules already built above) and the gather query
    // (sphere IS + any-hit only, no closest-hit — see __anyhit__gather).
    OptixProgramGroupDesc photonRaygenDesc{};
    photonRaygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    photonRaygenDesc.raygen.module = module;
    photonRaygenDesc.raygen.entryFunctionName = "__raygen__photon";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &photonRaygenDesc, 1, &pgOptions, LOG, &LOG_SIZE, &photonRaygenPG));

    OptixProgramGroupDesc photonMissDesc{};
    photonMissDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    photonMissDesc.miss.module = module;
    photonMissDesc.miss.entryFunctionName = "__miss__photon";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &photonMissDesc, 1, &pgOptions, LOG, &LOG_SIZE, &photonMissPG));

    OptixProgramGroupDesc photonHitTriDesc{};
    photonHitTriDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    photonHitTriDesc.hitgroup.moduleCH = module;
    photonHitTriDesc.hitgroup.entryFunctionNameCH = "__closesthit__photon";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &photonHitTriDesc, 1, &pgOptions, LOG, &LOG_SIZE, &photonHitTrianglePG));

    OptixProgramGroupDesc photonHitSphereDesc{};
    photonHitSphereDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    photonHitSphereDesc.hitgroup.moduleCH = module;
    photonHitSphereDesc.hitgroup.entryFunctionNameCH = "__closesthit__photon";
    photonHitSphereDesc.hitgroup.moduleIS = sphereModule;
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &photonHitSphereDesc, 1, &pgOptions, LOG, &LOG_SIZE, &photonHitSpherePG));

    OptixProgramGroupDesc gatherHitDesc{};
    gatherHitDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    gatherHitDesc.hitgroup.moduleAH = module;
    gatherHitDesc.hitgroup.entryFunctionNameAH = "__anyhit__gather";
    gatherHitDesc.hitgroup.moduleIS = sphereModule; // photons are spheres of radius photonGatherRadius
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &gatherHitDesc, 1, &pgOptions, LOG, &LOG_SIZE, &gatherHitPG));

    OptixProgramGroupDesc gatherMissDesc{};
    gatherMissDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    gatherMissDesc.miss.module = module;
    gatherMissDesc.miss.entryFunctionName = "__miss__gather";
    OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &gatherMissDesc, 1, &pgOptions, LOG, &LOG_SIZE, &gatherMissPG));

    // Phase 10 denoiser: raygen-only, never calls optixTrace.
    OptixProgramGroupDesc tonemapRaygenDesc{};
    tonemapRaygenDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    tonemapRaygenDesc.raygen.module = module;
    tonemapRaygenDesc.raygen.entryFunctionName = "__raygen__tonemap";
    OPTIX_CHECK_LOG(
        optixProgramGroupCreate(context, &tonemapRaygenDesc, 1, &pgOptions, LOG, &LOG_SIZE, &tonemapRaygenPG));
  }

  void buildPipeline() {
    OptixProgramGroup groups[] = {raygenPG,       missRadiancePG,      missOcclusionPG,   hitTrianglePG,
                                   hitSpherePG,    hitVoxelPG,          hitSdfPG,          photonRaygenPG,
                                   photonMissPG,   photonHitTrianglePG, photonHitSpherePG, gatherHitPG,
                                   gatherMissPG,   tonemapRaygenPG};
    OptixPipelineLinkOptions linkOptions{};
    // raygen -> radiance hit -> occlusion shadow ray (2), or raygen ->
    // radiance hit -> gather query (2), or photon-raygen -> photon-hit (1,
    // no nested trace) — 2 covers every path in this pipeline.
    const uint32_t maxTraceDepth = 2;
    linkOptions.maxTraceDepth = maxTraceDepth;
    OPTIX_CHECK_LOG(optixPipelineCreate(context, &pipelineCompileOptions, &linkOptions, groups,
                                         sizeof(groups) / sizeof(groups[0]), LOG, &LOG_SIZE, &pipeline));

    OptixStackSizes stackSizes{};
    for (auto *g : groups)
      OPTIX_CHECK(optixUtilAccumulateStackSizes(g, &stackSizes, pipeline));
    uint32_t dcFromTraversal, dcFromState, contStack;
    OPTIX_CHECK(optixUtilComputeStackSizes(&stackSizes, maxTraceDepth, 0, 0, &dcFromTraversal, &dcFromState,
                                            &contStack));
    // 2, not 1: single-level instancing means a 2-deep traversable graph
    // (top-level IAS -> per-object GAS).
    OPTIX_CHECK(optixPipelineSetStackSize(pipeline, dcFromTraversal, dcFromState, contStack, 2));
  }

  CUdeviceptr uploadTriangles(const std::vector<float3> &verts) {
    CUdeviceptr d;
    const size_t bytes = verts.size() * sizeof(float3);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d), bytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d), verts.data(), bytes, cudaMemcpyHostToDevice));
    return d;
  }

  SceneObject buildTriangleObject(const std::vector<float3> &verts, HitGroupData material) {
    SceneObject obj;
    obj.kind = GeometryKind::Triangle;
    obj.material = material;

    CUdeviceptr vertexBuffer = uploadTriangles(verts);

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
    input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
    input.triangleArray.vertexStrideInBytes = sizeof(float3);
    input.triangleArray.numVertices = static_cast<unsigned int>(verts.size());
    input.triangleArray.vertexBuffers = &vertexBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.triangleArray.flags = flags;
    input.triangleArray.numSbtRecords = 1;

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));

    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&obj.gasBuffer), sizes.outputSizeInBytes));

    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 obj.gasBuffer, sizes.outputSizeInBytes, &obj.gas, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    return obj;
  }

  SceneObject buildSphereObject(float3 center, float radius, HitGroupData material) {
    SceneObject obj;
    obj.kind = GeometryKind::Sphere;
    obj.material = material;

    CUdeviceptr vertexBuffer, radiusBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&vertexBuffer), sizeof(float3)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(vertexBuffer), &center, sizeof(float3), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&radiusBuffer), sizeof(float)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(radiusBuffer), &radius, sizeof(float), cudaMemcpyHostToDevice));

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_SPHERES;
    input.sphereArray.vertexBuffers = &vertexBuffer;
    input.sphereArray.numVertices = 1;
    input.sphereArray.radiusBuffers = &radiusBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.sphereArray.flags = flags;
    input.sphereArray.numSbtRecords = 1;

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));

    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&obj.gasBuffer), sizes.outputSizeInBytes));

    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 obj.gasBuffer, sizes.outputSizeInBytes, &obj.gas, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    cudaFree(reinterpret_cast<void *>(radiusBuffer));
    return obj;
  }

  // Adds a rectangular emissive object at the given corner/edges, both as
  // real (camera-visible) geometry and as the analytic params.light used for
  // NEE — shared by the fixed bring-up scene and the GLB-mesh/voxel/sdf
  // scenes, which all need *something* to light the object when there's no
  // environment map active (the two lighting modes aren't blended: an
  // environment supersedes the quad light entirely, see Params::envTex).
  void addLightQuad(float3 corner, float3 v1, float3 v2, float3 emission) {
    if (hasEnvironment)
      return;
    light.corner = corner;
    light.v1 = v1;
    light.v2 = v2;
    light.normal = normalize(cross(v1, v2));
    light.emission = emission;

    HitGroupData lightMat{};
    lightMat.materialType = MATERIAL_LIGHT;
    lightMat.emission = emission;
    objects.push_back(buildTriangleObject(
        {corner, corner + v1, corner + v1 + v2, corner, corner + v1 + v2, corner + v2}, lightMat));
  }

  SceneObject buildMeshObject(const MeshAsset &mesh) {
    SceneObject obj;
    obj.kind = GeometryKind::Triangle;
    obj.material.materialType = MATERIAL_TEXTURED_DIFFUSE;
    obj.material.albedo = toFloat3(mesh.baseColorFactor);

    std::vector<float3> positions(mesh.positions.size());
    for (size_t i = 0; i < mesh.positions.size(); ++i)
      positions[i] = toFloat3(mesh.positions[i]);

    const size_t normalBytes = mesh.normals.size() * sizeof(float3);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&meshNormals), normalBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(meshNormals), mesh.normals.data(), normalBytes,
                           cudaMemcpyHostToDevice));
    obj.material.normals = reinterpret_cast<float3 *>(meshNormals);

    if (!mesh.uvs.empty()) {
      const size_t uvBytes = mesh.uvs.size() * sizeof(float2);
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&meshUvs), uvBytes));
      CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(meshUvs), mesh.uvs.data(), uvBytes, cudaMemcpyHostToDevice));
      obj.material.uvs = reinterpret_cast<float2 *>(meshUvs);
    }

    if (mesh.hasBaseColorTexture) {
      const cudaChannelFormatDesc desc = cudaCreateChannelDesc<uchar4>();
      CUDA_CHECK(cudaMallocArray(&baseColorArray, &desc, mesh.baseColorTexture.width, mesh.baseColorTexture.height));
      CUDA_CHECK(cudaMemcpy2DToArray(baseColorArray, 0, 0, mesh.baseColorTexture.pixelsRGBA.data(),
                                      mesh.baseColorTexture.width * 4, mesh.baseColorTexture.width * 4,
                                      mesh.baseColorTexture.height, cudaMemcpyHostToDevice));
      cudaResourceDesc resDesc{};
      resDesc.resType = cudaResourceTypeArray;
      resDesc.res.array.array = baseColorArray;
      cudaTextureDesc texDesc{};
      texDesc.addressMode[0] = cudaAddressModeWrap;
      texDesc.addressMode[1] = cudaAddressModeWrap;
      texDesc.filterMode = cudaFilterModeLinear;
      texDesc.readMode = cudaReadModeNormalizedFloat;
      texDesc.normalizedCoords = 1;
      // glTF baseColorTexture is sRGB-encoded (baseColorFactor is linear,
      // only the texture needs decoding) — without this the path tracer's
      // linear-space lighting math treats gamma-encoded bytes as if they
      // were already linear, systematically darkening midtones. CUDA does
      // the sRGB->linear conversion in texture hardware, so this is free.
      texDesc.sRGB = 1;
      CUDA_CHECK(cudaCreateTextureObject(&baseColorTexObj, &resDesc, &texDesc, nullptr));
      obj.material.baseColorTex = baseColorTexObj;
    }

    CUdeviceptr vertexBuffer = uploadTriangles(positions);
    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
    input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
    input.triangleArray.vertexStrideInBytes = sizeof(float3);
    input.triangleArray.numVertices = static_cast<unsigned int>(positions.size());
    input.triangleArray.vertexBuffers = &vertexBuffer;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.triangleArray.flags = flags;
    input.triangleArray.numSbtRecords = 1;

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&obj.gasBuffer), sizes.outputSizeInBytes));
    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 obj.gasBuffer, sizes.outputSizeInBytes, &obj.gas, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    cudaFree(reinterpret_cast<void *>(vertexBuffer));
    return obj;
  }

  SceneObject buildVoxelObject(const VoxelGrid &grid) {
    SceneObject obj;
    obj.kind = GeometryKind::Voxel;
    obj.material.materialType = MATERIAL_VOXEL;

    std::vector<OptixAabb> aabbs(grid.cells.size());
    for (size_t i = 0; i < grid.cells.size(); ++i) {
      const glm::vec3 mn = grid.cellMin(grid.cells[i]);
      const glm::vec3 mx = grid.cellMax(grid.cells[i]);
      aabbs[i] = OptixAabb{mn.x, mn.y, mn.z, mx.x, mx.y, mx.z};
    }
    const size_t aabbBytes = aabbs.size() * sizeof(OptixAabb);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&voxelAabbBuffer), aabbBytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(voxelAabbBuffer), aabbs.data(), aabbBytes, cudaMemcpyHostToDevice));
    obj.material.voxelAabbs = reinterpret_cast<OptixAabb *>(voxelAabbBuffer);

    std::vector<float3> colors(grid.colors.size());
    for (size_t i = 0; i < grid.colors.size(); ++i)
      colors[i] = toFloat3(grid.colors[i]);
    const size_t colorBytes = colors.size() * sizeof(float3);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&voxelColorBuffer), colorBytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(voxelColorBuffer), colors.data(), colorBytes, cudaMemcpyHostToDevice));
    obj.material.voxelColors = reinterpret_cast<float3 *>(voxelColorBuffer);

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &voxelAabbBuffer;
    input.customPrimitiveArray.numPrimitives = static_cast<unsigned int>(aabbs.size());
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&obj.gasBuffer), sizes.outputSizeInBytes));
    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 obj.gasBuffer, sizes.outputSizeInBytes, &obj.gas, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    return obj;
  }

  // Single custom primitive covering the whole SDF grid's bounding box —
  // unlike voxels there's no sparse-cell array, just one continuous field
  // that __intersection__sdf sphere-traces through.
  SceneObject buildSdfObject(const SdfGrid &grid) {
    SceneObject obj;
    obj.kind = GeometryKind::Sdf;
    obj.material.materialType = MATERIAL_SDF;
    obj.material.albedo = toFloat3(grid.tintColor);
    obj.material.sdfOrigin = toFloat3(grid.origin);
    obj.material.sdfVoxelSize = grid.voxelSize;
    obj.material.sdfNx = grid.nx;
    obj.material.sdfNy = grid.ny;
    obj.material.sdfNz = grid.nz;

    const size_t bytes = grid.distances.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&sdfDistanceBuffer), bytes));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(sdfDistanceBuffer), grid.distances.data(), bytes, cudaMemcpyHostToDevice));
    obj.material.sdfDistances = reinterpret_cast<float *>(sdfDistanceBuffer);

    const glm::vec3 boundsMax = grid.boundsMax();
    OptixAabb aabb{grid.origin.x, grid.origin.y, grid.origin.z, boundsMax.x, boundsMax.y, boundsMax.z};
    CUdeviceptr aabbBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&aabbBuffer), sizeof(OptixAabb)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(aabbBuffer), &aabb, sizeof(OptixAabb), cudaMemcpyHostToDevice));

    OptixBuildInput input{};
    input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    input.customPrimitiveArray.aabbBuffers = &aabbBuffer;
    input.customPrimitiveArray.numPrimitives = 1;
    static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
    input.customPrimitiveArray.flags = flags;
    input.customPrimitiveArray.numSbtRecords = 1;

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&obj.gasBuffer), sizes.outputSizeInBytes));
    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                 obj.gasBuffer, sizes.outputSizeInBytes, &obj.gas, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    cudaFree(reinterpret_cast<void *>(aabbBuffer)); // only fed the build, not read at intersection time (unlike voxels)
    return obj;
  }

  void buildFixedTestScene() {
    HitGroupData groundMat{};
    groundMat.materialType = MATERIAL_DIFFUSE;
    groundMat.albedo = make_float3(0.72f, 0.72f, 0.7f);
    objects.push_back(buildTriangleObject(
        {
            make_float3(-3, -1, -3),
            make_float3(3, -1, -3),
            make_float3(3, -1, 3),
            make_float3(-3, -1, -3),
            make_float3(3, -1, 3),
            make_float3(-3, -1, 3),
        },
        groundMat));

    addLightQuad(make_float3(-0.6f, 2.9f, -0.6f), make_float3(1.2f, 0, 0), make_float3(0, 0, 1.2f),
                 make_float3(15.0f, 15.0f, 13.0f));

    HitGroupData diffuseMat{};
    diffuseMat.materialType = MATERIAL_DIFFUSE;
    diffuseMat.albedo = make_float3(0.75f, 0.22f, 0.2f);
    objects.push_back(buildSphereObject(make_float3(-1.2f, -0.3f, 0.0f), 0.7f, diffuseMat));

    HitGroupData mirrorMat{};
    mirrorMat.materialType = MATERIAL_MIRROR;
    mirrorMat.albedo = make_float3(0.9f, 0.9f, 0.92f);
    objects.push_back(buildSphereObject(make_float3(0.5f, -0.3f, 0.9f), 0.7f, mirrorMat));

    HitGroupData glassMat{};
    glassMat.materialType = MATERIAL_GLASS;
    glassMat.albedo = make_float3(1.0f, 1.0f, 1.0f);
    glassMat.ior = 1.5f;
    // Floating above the plane (not resting on it) on purpose: refracted
    // rays need room to converge before hitting a receiving surface, or the
    // caustic never has a chance to focus — standard practice for a
    // glass-caustic demo scene, not a physical-plausibility slip.
    objects.push_back(buildSphereObject(make_float3(1.4f, 0.5f, -0.6f), 0.6f, glassMat));

    boundsCenter = glm::vec3(0.0f, 0.2f, 0.0f);
    boundsRadius = 3.0f;

    // Caustics only make sense here: this is the only scene with specular
    // (mirror/glass) objects to seed one from. Requires the quad light
    // (addLightQuad already skipped it if hasEnvironment is set).
    enablePhotonMapping = !hasEnvironment;
  }

  // Key light sized/positioned relative to a bounding sphere so it's sensible
  // regardless of the loaded asset's own scale — shared by the mesh and
  // voxel scenes, which both need *something* to be lit by (no HDRI yet).
  void addBoundsKeyLight(const glm::vec3 &center, float radius) {
    const float3 c = toFloat3(center);
    const float r = radius;
    addLightQuad(make_float3(c.x - r, c.y + r * 2.2f, c.z - r), make_float3(r * 2.0f, 0, 0),
                 make_float3(0, 0, r * 2.0f), make_float3(20.0f, 20.0f, 18.0f));
  }

  void buildMeshScene(const MeshAsset &mesh) {
    objects.push_back(buildMeshObject(mesh));
    boundsCenter = mesh.boundsCenter();
    boundsRadius = std::max(mesh.boundsRadius(), 1e-3f);
    addBoundsKeyLight(boundsCenter, boundsRadius);
  }

  void buildVoxelScene(const VoxelGrid &grid) {
    objects.push_back(buildVoxelObject(grid));
    glm::vec3 mn(1e30f), mx(-1e30f);
    for (const glm::ivec3 &c : grid.cells) {
      mn = glm::min(mn, grid.cellMin(c));
      mx = glm::max(mx, grid.cellMax(c));
    }
    boundsCenter = (mn + mx) * 0.5f;
    boundsRadius = std::max(glm::length(mx - mn) * 0.5f, 1e-3f);
    addBoundsKeyLight(boundsCenter, boundsRadius);
  }

  void buildSdfScene(const SdfGrid &grid) {
    objects.push_back(buildSdfObject(grid));
    const glm::vec3 mx = grid.boundsMax();
    boundsCenter = (grid.origin + mx) * 0.5f;
    boundsRadius = std::max(glm::length(mx - grid.origin) * 0.5f, 1e-3f);
    addBoundsKeyLight(boundsCenter, boundsRadius);
  }

  // Uploads the environment map's pixels (as a bilinear-filtered float
  // texture — HDR data is already linear radiance, no sRGB conversion) and
  // its importance-sampling CDFs as plain device buffers (manual binary
  // search on the device, same "flat buffer, no texture-hardware tricks"
  // choice as the SDF grid — simpler and plenty fast at these sizes).
  void buildEnvironment(const EnvironmentMap &env) {
    hasEnvironment = true;
    envWidth = env.width;
    envHeight = env.height;

    std::vector<float4> rgba(static_cast<size_t>(env.width) * env.height);
    for (size_t i = 0; i < rgba.size(); ++i)
      rgba[i] = make_float4(env.pixels[i * 3 + 0], env.pixels[i * 3 + 1], env.pixels[i * 3 + 2], 1.0f);

    const cudaChannelFormatDesc desc = cudaCreateChannelDesc<float4>();
    CUDA_CHECK(cudaMallocArray(&envArray, &desc, env.width, env.height));
    CUDA_CHECK(cudaMemcpy2DToArray(envArray, 0, 0, rgba.data(), env.width * sizeof(float4), env.width * sizeof(float4),
                                    env.height, cudaMemcpyHostToDevice));
    cudaResourceDesc resDesc{};
    resDesc.resType = cudaResourceTypeArray;
    resDesc.res.array.array = envArray;
    cudaTextureDesc texDesc{};
    texDesc.addressMode[0] = cudaAddressModeWrap;  // u: wraps around the horizon
    texDesc.addressMode[1] = cudaAddressModeClamp; // v: clamp at the poles
    texDesc.filterMode = cudaFilterModeLinear;
    texDesc.readMode = cudaReadModeElementType; // already linear float radiance, no normalization/sRGB
    texDesc.normalizedCoords = 1;
    CUDA_CHECK(cudaCreateTextureObject(&envTexObj, &resDesc, &texDesc, nullptr));

    const size_t marginalBytes = env.marginalCdf.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&envMarginalCdfBuffer), marginalBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(envMarginalCdfBuffer), env.marginalCdf.data(), marginalBytes,
                           cudaMemcpyHostToDevice));

    const size_t conditionalBytes = env.conditionalCdf.size() * sizeof(float);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&envConditionalCdfBuffer), conditionalBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(envConditionalCdfBuffer), env.conditionalCdf.data(),
                           conditionalBytes, cudaMemcpyHostToDevice));
  }

  void buildScene(const SceneSource &source) {
    // Must happen before any of the geometry-building calls below: they
    // consult hasEnvironment (via addLightQuad) to decide whether to add a
    // synthetic quad light.
    if (source.environment)
      buildEnvironment(*source.environment);

    if (source.sdf)
      buildSdfScene(*source.sdf);
    else if (source.voxels)
      buildVoxelScene(*source.voxels);
    else if (source.mesh)
      buildMeshScene(*source.mesh);
    else
      buildFixedTestScene();

    buildIAS();

    if (enablePhotonMapping) {
      buildPhotonSbt();
      photonRadius = boundsRadius * 0.05f;
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&photonBuffer), sizeof(Photon) * kPhotonCapacity));
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&photonCounterBuffer), sizeof(unsigned int)));
    }
  }

  // A second SBT sharing this same pipeline, used only for the photon-
  // emission launch. optixLaunch's SBT argument is what resolves every
  // trace call's hit-group/miss index for programs invoked *by* that
  // launch (raygen and anything reached from it) — so __raygen__photon's
  // own optixTrace(params.handle, ..., sbtOffset=<object index>, ...) calls
  // resolve against *this* table, reaching __closesthit__photon for the
  // same objects that radianceSbt resolves to __closesthit__radiance.
  // That's the whole reason this needs to be a separate table rather than
  // extending radianceSbt (like the gather hit-group is): the emission
  // raygen hits the *same* scene instances as the camera raygen, and
  // instance.sbtOffset is baked into the IAS at object-index granularity,
  // not ray-type granularity — a second SBT sidesteps needing to introduce
  // ray-type-multiplexed indexing (sbtOffset*RAY_TYPE_COUNT+rayType) into
  // the already-verified radiance/occlusion indexing at all.
  void buildPhotonSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(photonRaygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));

    MissRecord missRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(photonMissPG, &missRecord));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_miss), &missRecord, sizeof(missRecord), cudaMemcpyHostToDevice));

    std::vector<HitGroupRecord> hitRecords(objects.size());
    for (size_t i = 0; i < objects.size(); ++i) {
      // Fixed test scene only ever has triangle/sphere objects (see
      // enablePhotonMapping) — no voxel/sdf case to handle here.
      OptixProgramGroup pg = objects[i].kind == GeometryKind::Sphere ? photonHitSpherePG : photonHitTrianglePG;
      OPTIX_CHECK(optixSbtRecordPackHeader(pg, &hitRecords[i]));
      hitRecords[i].data = objects[i].material;
    }
    CUdeviceptr d_hit;
    const size_t hitBytes = hitRecords.size() * sizeof(HitGroupRecord);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hit), hitBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hit), hitRecords.data(), hitBytes, cudaMemcpyHostToDevice));

    photonSbt.raygenRecord = d_rg;
    photonSbt.missRecordBase = d_miss;
    photonSbt.missRecordStrideInBytes = sizeof(MissRecord);
    photonSbt.missRecordCount = 1;
    photonSbt.hitgroupRecordBase = d_hit;
    photonSbt.hitgroupRecordStrideInBytes = sizeof(HitGroupRecord);
    photonSbt.hitgroupRecordCount = static_cast<unsigned int>(hitRecords.size());
  }

  // Emits one pass of photons (the caller must already have uploaded a
  // Params with photons/photonCounter/photonCapacity/photonBatchSize/light/
  // handle set, for the emission launch itself to read), then rebuilds the
  // photon BVH (a GAS of uniform-radius spheres, one per deposited photon).
  // Returns the radius baked into that GAS — the caller needs this exact
  // value for the *next* Params upload (params.photonGatherRadius), since
  // photonRadius itself is shrunk here in preparation for next pass and no
  // longer matches what was just built. Called once per render() call — see
  // that function for why camera movement doesn't reset any of this (the
  // photon map is view-independent).
  float tracePhotonPass() {
    const float radiusThisPass = photonRadius;
    CUDA_CHECK(cudaMemsetAsync(reinterpret_cast<void *>(photonCounterBuffer), 0, sizeof(unsigned int), stream));
    OPTIX_CHECK(optixLaunch(pipeline, stream, paramsBuffer, sizeof(Params), &photonSbt, kPhotonBatchSize, 1, 1));

    unsigned int deposited = 0;
    CUDA_CHECK(cudaMemcpyAsync(&deposited, reinterpret_cast<void *>(photonCounterBuffer), sizeof(unsigned int),
                               cudaMemcpyDeviceToHost, stream));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    deposited = std::min(deposited, kPhotonCapacity);
    if (photonPassIndex < 3 || photonPassIndex % 64 == 0)
      std::fprintf(stderr, "italy: photon pass %u: %u caustic photons deposited (radius %.4f)\n", photonPassIndex,
                   deposited, radiusThisPass);

    if (deposited > 0) {
      if (photonGasBuffer) {
        cudaFree(reinterpret_cast<void *>(photonGasBuffer));
        photonGasBuffer = 0;
      }
      if (photonGasVertexBuffer) {
        cudaFree(reinterpret_cast<void *>(photonGasVertexBuffer));
        photonGasVertexBuffer = 0;
      }
      if (photonGasRadiusBuffer) {
        cudaFree(reinterpret_cast<void *>(photonGasRadiusBuffer));
        photonGasRadiusBuffer = 0;
      }

      // The sphere build input wants a plain position buffer, but Photon
      // interleaves position/direction/power — extract just the positions
      // rather than fighting a non-float3 stride through the sphere API.
      std::vector<Photon> photonsHost(deposited);
      CUDA_CHECK(cudaMemcpy(photonsHost.data(), reinterpret_cast<void *>(photonBuffer), deposited * sizeof(Photon),
                             cudaMemcpyDeviceToHost));
      std::vector<float3> positions(deposited);
      for (unsigned int i = 0; i < deposited; ++i)
        positions[i] = photonsHost[i].position;

      CUDA_CHECK(
          cudaMalloc(reinterpret_cast<void **>(&photonGasVertexBuffer), deposited * sizeof(float3)));
      CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(photonGasVertexBuffer), positions.data(),
                             deposited * sizeof(float3), cudaMemcpyHostToDevice));
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&photonGasRadiusBuffer), sizeof(float)));
      CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(photonGasRadiusBuffer), &radiusThisPass, sizeof(float),
                             cudaMemcpyHostToDevice));

      OptixBuildInput input{};
      input.type = OPTIX_BUILD_INPUT_TYPE_SPHERES;
      input.sphereArray.vertexBuffers = &photonGasVertexBuffer;
      input.sphereArray.numVertices = deposited;
      input.sphereArray.radiusBuffers = &photonGasRadiusBuffer;
      input.sphereArray.singleRadius = 1;
      static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
      input.sphereArray.flags = flags;
      input.sphereArray.numSbtRecords = 1;

      OptixAccelBuildOptions accelOptions{};
      accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
      accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
      OptixAccelBufferSizes sizes{};
      OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
      CUdeviceptr tempBuffer;
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
      CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&photonGasBuffer), sizes.outputSizeInBytes));
      OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes,
                                   photonGasBuffer, sizes.outputSizeInBytes, &photonGasHandle, nullptr, 0));
      CUDA_CHECK(cudaStreamSynchronize(stream));
      cudaFree(reinterpret_cast<void *>(tempBuffer));
    } else {
      photonGasHandle = 0; // no caustic photons yet this run — gather becomes a no-op (see photonHandle==0 check)
    }

    totalPhotonsEmitted += kPhotonBatchSize;
    // Original (non-stochastic-per-point) PPM radius decay, Hachisuka/Ogaki/
    // Jensen 2008: R shrinks roughly as 1/sqrt(pass index), guaranteeing the
    // density-estimate bias vanishes as passes -> infinity.
    photonRadius *= std::sqrt((photonPassIndex + kPpmAlpha) / (photonPassIndex + 1.0f));
    ++photonPassIndex;
    return radiusThisPass;
  }

  void buildIAS() {
    // Instance acceleration structure over the objects built above.
    std::vector<OptixInstance> instances(objects.size());
    static const float identity[12] = {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0};
    for (size_t i = 0; i < objects.size(); ++i) {
      OptixInstance &inst = instances[i];
      std::memset(&inst, 0, sizeof(inst));
      std::memcpy(inst.transform, identity, sizeof(identity));
      inst.instanceId = static_cast<unsigned int>(i);
      inst.visibilityMask = 1;
      inst.sbtOffset = static_cast<unsigned int>(i);
      inst.flags = OPTIX_INSTANCE_FLAG_NONE;
      inst.traversableHandle = objects[i].gas;
    }

    CUdeviceptr instanceBuffer;
    const size_t instBytes = instances.size() * sizeof(OptixInstance);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&instanceBuffer), instBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(instanceBuffer), instances.data(), instBytes,
                           cudaMemcpyHostToDevice));

    OptixBuildInput iasInput{};
    iasInput.type = OPTIX_BUILD_INPUT_TYPE_INSTANCES;
    iasInput.instanceArray.instances = instanceBuffer;
    iasInput.instanceArray.numInstances = static_cast<unsigned int>(instances.size());

    OptixAccelBuildOptions accelOptions{};
    accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
    accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes sizes{};
    OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &iasInput, 1, &sizes));
    CUdeviceptr tempBuffer;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&iasBuffer), sizes.outputSizeInBytes));
    OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &iasInput, 1, tempBuffer, sizes.tempSizeInBytes,
                                 iasBuffer, sizes.outputSizeInBytes, &iasHandle, nullptr, 0));
    CUDA_CHECK(cudaStreamSynchronize(stream));
    cudaFree(reinterpret_cast<void *>(tempBuffer));
    cudaFree(reinterpret_cast<void *>(instanceBuffer));
  }

  void buildSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(raygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));

    // Miss index 2 (__miss__gather) backs the photon gather query issued
    // from inside __closesthit__radiance — see Params::photonHandle. It's
    // appended unconditionally (harmless/unused when there's no photon map)
    // rather than only when enablePhotonMapping, since the alternative is a
    // second SBT-layout variant to keep straight.
    MissRecord missRecords[3]{};
    OPTIX_CHECK(optixSbtRecordPackHeader(missRadiancePG, &missRecords[0]));
    missRecords[0].data.bgColor = make_float3(0.05f, 0.06f, 0.08f);
    OPTIX_CHECK(optixSbtRecordPackHeader(missOcclusionPG, &missRecords[1]));
    OPTIX_CHECK(optixSbtRecordPackHeader(gatherMissPG, &missRecords[2]));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecords)));
    CUDA_CHECK(
        cudaMemcpy(reinterpret_cast<void *>(d_miss), missRecords, sizeof(missRecords), cudaMemcpyHostToDevice));

    // One extra record past the per-object ones, for the gather hit-group —
    // see Params::gatherHitSbtOffset for why it has to live at a
    // scene-object-count-dependent index rather than a fixed one.
    gatherHitSbtOffset = static_cast<unsigned int>(objects.size());
    std::vector<HitGroupRecord> hitRecords(objects.size() + 1);
    for (size_t i = 0; i < objects.size(); ++i) {
      OptixProgramGroup pg;
      switch (objects[i].kind) {
      case GeometryKind::Sphere:
        pg = hitSpherePG;
        break;
      case GeometryKind::Voxel:
        pg = hitVoxelPG;
        break;
      case GeometryKind::Sdf:
        pg = hitSdfPG;
        break;
      default:
        pg = hitTrianglePG;
        break;
      }
      OPTIX_CHECK(optixSbtRecordPackHeader(pg, &hitRecords[i]));
      hitRecords[i].data = objects[i].material;
    }
    OPTIX_CHECK(optixSbtRecordPackHeader(gatherHitPG, &hitRecords[gatherHitSbtOffset]));
    CUdeviceptr d_hit;
    const size_t hitBytes = hitRecords.size() * sizeof(HitGroupRecord);
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hit), hitBytes));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hit), hitRecords.data(), hitBytes, cudaMemcpyHostToDevice));

    sbt.raygenRecord = d_rg;
    sbt.missRecordBase = d_miss;
    sbt.missRecordStrideInBytes = sizeof(MissRecord);
    sbt.missRecordCount = 3;
    sbt.hitgroupRecordBase = d_hit;
    sbt.hitgroupRecordStrideInBytes = sizeof(HitGroupRecord);
    sbt.hitgroupRecordCount = static_cast<unsigned int>(hitRecords.size());
  }

  // Phase 10: the OptiX AI denoiser, color-only (no albedo/normal guide
  // buffers — a real quality improvement but it means threading first-hit
  // G-buffers out of the path tracer too, a natural upgrade rather than
  // required for "wire in the denoiser"). hdrIntensity is left null in
  // OptixDenoiserParams at invoke time (see render()), which the API
  // documents as "autoexposure will be calculated automatically" — good
  // enough for MVP, skips needing a separate optixDenoiserComputeIntensity
  // pass.
  void buildDenoiser(int width, int height) {
    OptixDenoiserOptions options{}; // guideAlbedo=0, guideNormal=0, denoiseAlpha=COPY(0)
    OPTIX_CHECK(optixDenoiserCreate(context, OPTIX_DENOISER_MODEL_KIND_HDR, &options, &denoiser));

    OptixDenoiserSizes sizes{};
    OPTIX_CHECK(optixDenoiserComputeMemoryResources(denoiser, static_cast<unsigned int>(width),
                                                     static_cast<unsigned int>(height), &sizes));
    denoiserStateSize = sizes.stateSizeInBytes;
    denoiserScratchSize = sizes.withoutOverlapScratchSizeInBytes;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&denoiserStateBuffer), denoiserStateSize));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&denoiserScratchBuffer), denoiserScratchSize));
    OPTIX_CHECK(optixDenoiserSetup(denoiser, stream, static_cast<unsigned int>(width),
                                    static_cast<unsigned int>(height), denoiserStateBuffer, denoiserStateSize,
                                    denoiserScratchBuffer, denoiserScratchSize));

    CUDA_CHECK(
        cudaMalloc(reinterpret_cast<void **>(&denoisedBuffer), static_cast<size_t>(width) * height * sizeof(float4)));
  }

  // Third SBT, same reasoning as photonSbt: __raygen__tonemap runs under its
  // own launch, and needs a raygen record packed for tonemapRaygenPG rather
  // than whatever's in radianceSbt's raygen slot. No miss/hitgroup records
  // at all (not just "unused, harmless" like photonSbt's radiance-table
  // reuse pattern elsewhere) — this raygen never calls optixTrace, so there
  // is nothing for those tables to ever be consulted for.
  void buildTonemapSbt() {
    RayGenRecord rgRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(tonemapRaygenPG, &rgRecord));
    CUdeviceptr d_rg;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));
    tonemapSbt.raygenRecord = d_rg;

    // OptiX validates that missRecordBase is non-null even though this
    // raygen never calls optixTrace and so can never actually reach a miss
    // program — "no miss table at all" (missRecordCount=0, base=nullptr, as
    // photonSbt's hitgroup table gets away with) isn't accepted for miss
    // specifically. gatherMissPG (an empty no-op, see __miss__gather) is a
    // convenient already-existing dummy target that's equally never invoked
    // here in practice.
    MissRecord missRecord{};
    OPTIX_CHECK(optixSbtRecordPackHeader(gatherMissPG, &missRecord));
    CUdeviceptr d_miss;
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_miss), sizeof(missRecord)));
    CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_miss), &missRecord, sizeof(missRecord), cudaMemcpyHostToDevice));
    tonemapSbt.missRecordBase = d_miss;
    tonemapSbt.missRecordStrideInBytes = sizeof(MissRecord);
    tonemapSbt.missRecordCount = 1;
  }

  void initGLInterop(int width, int height) {
    const auto &gl = GLBufferFns::get();
    gl.glGenBuffers(1, &pbo);
    gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, pbo);
    gl.glBufferData(GL_PIXEL_UNPACK_BUFFER, static_cast<ptrdiff_t>(width) * height * 4, nullptr, GL_STREAM_DRAW);
    gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0);
    CUDA_CHECK(cudaGraphicsGLRegisterBuffer(&cudaPbo, pbo, cudaGraphicsRegisterFlagsWriteDiscard));

    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&accumBuffer),
                           static_cast<size_t>(width) * height * sizeof(float4)));
    CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&paramsBuffer), sizeof(Params)));
  }
};

OptixRenderer::OptixRenderer(int width, int height, const SceneSource &source)
    : impl_(new Impl()), width_(width), height_(height) {
  impl_->initContext();
  impl_->buildModule();
  impl_->buildProgramGroups();
  impl_->buildPipeline();
  impl_->buildScene(source);
  impl_->buildSbt();
  impl_->buildTonemapSbt();
  impl_->initGLInterop(width, height);
  impl_->buildDenoiser(width, height);

  sceneBoundsCenter_ = impl_->boundsCenter;
  sceneBoundsRadius_ = impl_->boundsRadius;

  glGenTextures(1, &glTexture_);
  glBindTexture(GL_TEXTURE_2D, glTexture_);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);
  glBindTexture(GL_TEXTURE_2D, 0);
}

OptixRenderer::~OptixRenderer() {
  if (glTexture_)
    glDeleteTextures(1, &glTexture_);
  delete impl_;
}

void OptixRenderer::resetAccumulation() { subframeIndex_ = 0; }

void OptixRenderer::render(const OrbitCamera &camera, unsigned int samplesPerLaunch, float exposure, bool denoise,
                            TonemapOperator tonemap) {
  const glm::vec3 eye = camera.position();
  const glm::vec3 target = camera.target();
  const glm::vec3 forward = glm::normalize(target - eye);
  const glm::vec3 worldUp(0, 1, 0);
  const glm::vec3 right = glm::normalize(glm::cross(forward, worldUp));
  const glm::vec3 up = glm::cross(right, forward);
  const float aspect = static_cast<float>(width_) / static_cast<float>(height_);
  const float tanHalfFov = std::tan(camera.fovYRadians * 0.5f);

  Params params{};
  params.subframeIndex = subframeIndex_;
  params.accumBuffer = reinterpret_cast<float4 *>(impl_->accumBuffer);
  params.width = static_cast<unsigned int>(width_);
  params.height = static_cast<unsigned int>(height_);
  params.samplesPerLaunch = samplesPerLaunch;
  params.exposure = exposure;
  params.tonemapOperator = static_cast<unsigned int>(tonemap);
  params.eye = toFloat3(eye);
  params.U = toFloat3(right * tanHalfFov * aspect);
  params.V = toFloat3(up * tanHalfFov);
  params.W = toFloat3(forward);
  params.light = impl_->light;
  params.handle = impl_->iasHandle;
  if (impl_->hasEnvironment) {
    params.envTex = impl_->envTexObj;
    params.envMarginalCdf = reinterpret_cast<float *>(impl_->envMarginalCdfBuffer);
    params.envConditionalCdf = reinterpret_cast<float *>(impl_->envConditionalCdfBuffer);
    params.envWidth = impl_->envWidth;
    params.envHeight = impl_->envHeight;
  }
  params.gatherHitSbtOffset = impl_->gatherHitSbtOffset;

  // Caustics: run one photon-emission pass and rebuild the photon BVH
  // *before* the main launch, so this frame's gather queries see it. Not
  // gated on camera movement (unlike accumBuffer/subframeIndex) — the
  // photon map doesn't depend on the camera at all, so it keeps
  // progressively refining regardless of orbiting/panning.
  if (impl_->enablePhotonMapping) {
    params.photons = reinterpret_cast<Photon *>(impl_->photonBuffer);
    params.photonCounter = reinterpret_cast<unsigned int *>(impl_->photonCounterBuffer);
    params.photonCapacity = Impl::kPhotonCapacity;
    params.photonBatchSize = Impl::kPhotonBatchSize;
    CUDA_CHECK(cudaMemcpyAsync(reinterpret_cast<void *>(impl_->paramsBuffer), &params, sizeof(Params),
                               cudaMemcpyHostToDevice, impl_->stream));
    const float radiusUsed = impl_->tracePhotonPass();
    params.photonHandle = impl_->photonGasHandle;
    params.photonGatherRadius = radiusUsed;
    params.totalPhotonsEmitted = impl_->totalPhotonsEmitted;
  }

  CUDA_CHECK(cudaGraphicsMapResources(1, &impl_->cudaPbo, impl_->stream));
  size_t mappedSize = 0;
  void *devicePtr = nullptr;
  CUDA_CHECK(cudaGraphicsResourceGetMappedPointer(&devicePtr, &mappedSize, impl_->cudaPbo));
  params.frameBuffer = reinterpret_cast<uchar4 *>(devicePtr);
  params.denoiserEnabled = denoise ? 1u : 0u;
  params.denoisedBuffer = reinterpret_cast<float4 *>(impl_->denoisedBuffer);

  CUDA_CHECK(cudaMemcpyAsync(reinterpret_cast<void *>(impl_->paramsBuffer), &params, sizeof(Params),
                             cudaMemcpyHostToDevice, impl_->stream));
  OPTIX_CHECK(optixLaunch(impl_->pipeline, impl_->stream, impl_->paramsBuffer, sizeof(Params), &impl_->sbt, width_,
                           height_, 1));

  if (denoise) {
    // Color-only denoising (no albedo/normal guide layers — see
    // buildDenoiser()'s comment), hdrIntensity left null so the denoiser
    // computes autoexposure internally rather than needing a separate
    // optixDenoiserComputeIntensity pass.
    OptixDenoiserParams denoiserParams{};

    OptixImage2D img{};
    img.width = static_cast<unsigned int>(width_);
    img.height = static_cast<unsigned int>(height_);
    img.rowStrideInBytes = static_cast<unsigned int>(width_) * sizeof(float4);
    img.pixelStrideInBytes = sizeof(float4);
    img.format = OPTIX_PIXEL_FORMAT_FLOAT4;

    OptixImage2D inputImg = img;
    inputImg.data = impl_->accumBuffer;
    OptixImage2D outputImg = img;
    outputImg.data = impl_->denoisedBuffer;

    OptixDenoiserLayer layer{};
    layer.input = inputImg;
    layer.output = outputImg;
    OptixDenoiserGuideLayer guideLayer{}; // all zero: no albedo/normal/flow guides

    OPTIX_CHECK(optixDenoiserInvoke(impl_->denoiser, impl_->stream, &denoiserParams, impl_->denoiserStateBuffer,
                                     impl_->denoiserStateSize, &guideLayer, &layer, 1, 0, 0,
                                     impl_->denoiserScratchBuffer, impl_->denoiserScratchSize));

    // params on the device already has the right frameBuffer/denoisedBuffer/
    // exposure for this — no need to re-upload before this second launch.
    OPTIX_CHECK(optixLaunch(impl_->pipeline, impl_->stream, impl_->paramsBuffer, sizeof(Params), &impl_->tonemapSbt,
                             width_, height_, 1));
  }

  CUDA_CHECK(cudaGraphicsUnmapResources(1, &impl_->cudaPbo, impl_->stream));
  CUDA_CHECK(cudaStreamSynchronize(impl_->stream));

  const auto &gl = GLBufferFns::get();
  gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, impl_->pbo);
  glBindTexture(GL_TEXTURE_2D, glTexture_);
  glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width_, height_, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);
  glBindTexture(GL_TEXTURE_2D, 0);
  gl.glBindBuffer(GL_PIXEL_UNPACK_BUFFER, 0);

  ++subframeIndex_;
}

} // namespace italy
