#include "convert/sdf_baker.h"

#include <optix.h>
// optix_function_table_definition.h deliberately NOT included here — it
// defines a process-wide global (g_optixFunctionTable_*) and must appear in
// exactly one translation unit across the whole binary. optix_renderer.cpp
// already provides it; this file just needs the declarations from
// optix_stubs.h to call into that same shared table.
#include <optix_stack_size.h>
#include <optix_stubs.h>

#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <vector>

#include <sutil/vec_math.h>

#include "render/kernels/sdf_bake_params.h"
#include "render/optix_check.h"
#include "render_config.h" // generated by CMake: kSdfBakeOptixIRPath

// monkey-boy: this builds and tears down its own OptixDeviceContext rather
// than sharing OptixRenderer's — baking runs once at load time, so the
// ~100-200ms of extra context/module setup is immaterial, and it keeps this
// file fully decoupled from OptixRenderer's internals (no shared-context
// plumbing across a header boundary for a one-shot preprocess). Revisit only
// if baking needs to happen repeatedly at interactive rates.

namespace italy {
namespace {

float3 toFloat3(const glm::vec3 &v) { return make_float3(v.x, v.y, v.z); }

std::vector<char> readFile(const char *path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f)
    throw std::runtime_error(std::string("cannot open ") + path);
  const auto size = f.tellg();
  std::vector<char> data(static_cast<size_t>(size));
  f.seekg(0);
  f.read(data.data(), size);
  return data;
}

void logCallback(unsigned int level, const char *tag, const char *message, void *) {
  std::fprintf(stderr, "[optix-bake][%u][%s] %s\n", level, tag, message);
}

// MATERIAL_SDF only gets one flat tint for the whole field (see its doc
// comment in pathtracer_params.h) — baseColorFactor alone would render as
// flat white for the common case of a textured material that leaves
// baseColorFactor at the glTF default (1,1,1) and puts all its color in the
// texture (true of the device-bottom.glb test asset), which would look like
// a broken feature rather than the documented simplification it is. Average
// the (sRGB-decoded) texture instead when one exists, same as glTF's own
// finalColor = baseColorFactor * baseColorTexture compositing.
glm::vec3 averageTintColor(const MeshAsset &mesh) {
  if (!mesh.hasBaseColorTexture)
    return mesh.baseColorFactor;
  const auto &tex = mesh.baseColorTexture;
  const size_t pixelCount = static_cast<size_t>(tex.width) * tex.height;
  if (pixelCount == 0)
    return mesh.baseColorFactor;
  auto srgbToLinear = [](float c) { return c <= 0.04045f ? c / 12.92f : std::pow((c + 0.055f) / 1.055f, 2.4f); };
  double sum[3] = {0, 0, 0};
  // Subsample for large textures — an average color doesn't need every texel.
  const size_t stride = std::max<size_t>(1, pixelCount / 4096);
  size_t sampled = 0;
  for (size_t p = 0; p < pixelCount; p += stride, ++sampled) {
    sum[0] += srgbToLinear(tex.pixelsRGBA[p * 4 + 0] / 255.0f);
    sum[1] += srgbToLinear(tex.pixelsRGBA[p * 4 + 1] / 255.0f);
    sum[2] += srgbToLinear(tex.pixelsRGBA[p * 4 + 2] / 255.0f);
  }
  return glm::vec3(sum[0] / sampled, sum[1] / sampled, sum[2] / sampled) * mesh.baseColorFactor;
}

template <typename T> struct SbtRecord {
  __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
  T data;
};

} // namespace

SdfGrid bakeSdf(const MeshAsset &mesh, int resolution) {
  SdfGrid grid;
  const glm::vec3 extent = mesh.boundsMax - mesh.boundsMin;
  const float longestAxis = std::max({extent.x, extent.y, extent.z, 1e-6f});
  grid.voxelSize = longestAxis / static_cast<float>(std::max(resolution, 1));

  // Pad the grid a couple of cells beyond the mesh's own bounding box so
  // sphere tracing has room to approach the surface from outside cleanly
  // rather than starting exactly at its edge.
  constexpr int kPad = 2;
  grid.origin = mesh.boundsMin - glm::vec3(grid.voxelSize * kPad);
  const glm::vec3 paddedExtent = extent + glm::vec3(grid.voxelSize * kPad * 2.0f);
  grid.nx = static_cast<int>(std::ceil(paddedExtent.x / grid.voxelSize)) + 1;
  grid.ny = static_cast<int>(std::ceil(paddedExtent.y / grid.voxelSize)) + 1;
  grid.nz = static_cast<int>(std::ceil(paddedExtent.z / grid.voxelSize)) + 1;
  grid.tintColor = averageTintColor(mesh);

  OptixDeviceContext context = nullptr;
  CUDA_CHECK(cudaFree(nullptr));
  OPTIX_CHECK(optixInit());
  OptixDeviceContextOptions ctxOptions{};
  ctxOptions.logCallbackFunction = &logCallback;
  ctxOptions.logCallbackLevel = 3;
  OPTIX_CHECK(optixDeviceContextCreate(nullptr, &ctxOptions, &context));

  CUstream stream;
  CUDA_CHECK(cudaStreamCreate(&stream));

  // Triangle GAS for the mesh, traced directly (no IAS — nothing else in
  // this pass needs one, and BakeParams.meshHandle is typed to expect it).
  std::vector<float3> positions(mesh.positions.size());
  for (size_t i = 0; i < mesh.positions.size(); ++i)
    positions[i] = toFloat3(mesh.positions[i]);

  CUdeviceptr vertexBuffer;
  const size_t vbytes = positions.size() * sizeof(float3);
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&vertexBuffer), vbytes));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(vertexBuffer), positions.data(), vbytes, cudaMemcpyHostToDevice));

  OptixBuildInput input{};
  input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
  input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
  input.triangleArray.vertexStrideInBytes = sizeof(float3);
  input.triangleArray.numVertices = static_cast<unsigned int>(positions.size());
  input.triangleArray.vertexBuffers = &vertexBuffer;
  static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
  input.triangleArray.flags = flags;
  input.triangleArray.numSbtRecords = 1;

  OptixAccelBuildOptions accelOptions{};
  accelOptions.buildFlags = OPTIX_BUILD_FLAG_NONE;
  accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
  OptixAccelBufferSizes sizes{};
  OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
  CUdeviceptr tempBuffer, gasBuffer;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&gasBuffer), sizes.outputSizeInBytes));
  OptixTraversableHandle gasHandle;
  OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes, gasBuffer,
                               sizes.outputSizeInBytes, &gasHandle, nullptr, 0));
  CUDA_CHECK(cudaStreamSynchronize(stream));
  cudaFree(reinterpret_cast<void *>(tempBuffer));
  cudaFree(reinterpret_cast<void *>(vertexBuffer));

  OptixPipelineCompileOptions pcOpts{};
  pcOpts.usesMotionBlur = false;
  pcOpts.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS; // raw GAS trace, no IAS
  pcOpts.numPayloadValues = 1;
  pcOpts.numAttributeValues = 2;
  pcOpts.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
  pcOpts.pipelineLaunchParamsVariableName = "params";
  pcOpts.usesPrimitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE;

  OptixModuleCompileOptions mcOpts{};
  mcOpts.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_3;
  mcOpts.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;

  OptixModule module;
  const std::vector<char> ir = readFile(kSdfBakeOptixIRPath);
  OPTIX_CHECK_LOG(optixModuleCreate(context, &mcOpts, &pcOpts, ir.data(), ir.size(), LOG, &LOG_SIZE, &module));

  OptixProgramGroupOptions pgOpts{};
  OptixProgramGroup raygenPG, missPG, hitPG;

  OptixProgramGroupDesc rgDesc{};
  rgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
  rgDesc.raygen.module = module;
  rgDesc.raygen.entryFunctionName = "__raygen__bake_sdf";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &rgDesc, 1, &pgOpts, LOG, &LOG_SIZE, &raygenPG));

  OptixProgramGroupDesc msDesc{};
  msDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
  msDesc.miss.module = module;
  msDesc.miss.entryFunctionName = "__miss__bake";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &msDesc, 1, &pgOpts, LOG, &LOG_SIZE, &missPG));

  OptixProgramGroupDesc hgDesc{};
  hgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
  hgDesc.hitgroup.moduleCH = module;
  hgDesc.hitgroup.entryFunctionNameCH = "__closesthit__bake";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hgDesc, 1, &pgOpts, LOG, &LOG_SIZE, &hitPG));

  OptixProgramGroup groups[] = {raygenPG, missPG, hitPG};
  OptixPipelineLinkOptions linkOpts{};
  linkOpts.maxTraceDepth = 1; // raygen calls optixTrace directly, no nested tracing
  OptixPipeline pipeline;
  OPTIX_CHECK_LOG(optixPipelineCreate(context, &pcOpts, &linkOpts, groups, 3, LOG, &LOG_SIZE, &pipeline));
  OptixStackSizes stackSizes{};
  for (auto *g : groups)
    OPTIX_CHECK(optixUtilAccumulateStackSizes(g, &stackSizes, pipeline));
  uint32_t dcFromTraversal, dcFromState, contStack;
  OPTIX_CHECK(optixUtilComputeStackSizes(&stackSizes, 1, 0, 0, &dcFromTraversal, &dcFromState, &contStack));
  OPTIX_CHECK(optixPipelineSetStackSize(pipeline, dcFromTraversal, dcFromState, contStack, 1));

  SbtRecord<BakeRayGenData> rgRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(raygenPG, &rgRecord));
  SbtRecord<BakeMissData> msRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(missPG, &msRecord));
  SbtRecord<BakeHitGroupData> hgRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(hitPG, &hgRecord));

  CUdeviceptr d_rg, d_ms, d_hg;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_ms), sizeof(msRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_ms), &msRecord, sizeof(msRecord), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hg), sizeof(hgRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hg), &hgRecord, sizeof(hgRecord), cudaMemcpyHostToDevice));

  OptixShaderBindingTable sbt{};
  sbt.raygenRecord = d_rg;
  sbt.missRecordBase = d_ms;
  sbt.missRecordStrideInBytes = sizeof(msRecord);
  sbt.missRecordCount = 1;
  sbt.hitgroupRecordBase = d_hg;
  sbt.hitgroupRecordStrideInBytes = sizeof(hgRecord);
  sbt.hitgroupRecordCount = 1;

  const size_t numCells = static_cast<size_t>(grid.nx) * grid.ny * grid.nz;
  CUdeviceptr outputBuffer;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&outputBuffer), numCells * sizeof(float)));

  BakeParams params{};
  params.meshHandle = gasHandle;
  params.gridOrigin = toFloat3(grid.origin);
  params.voxelSize = grid.voxelSize;
  params.nx = static_cast<unsigned int>(grid.nx);
  params.ny = static_cast<unsigned int>(grid.ny);
  params.nz = static_cast<unsigned int>(grid.nz);
  params.output = reinterpret_cast<float *>(outputBuffer);

  CUdeviceptr d_params;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_params), sizeof(params)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_params), &params, sizeof(params), cudaMemcpyHostToDevice));

  OPTIX_CHECK(optixLaunch(pipeline, stream, d_params, sizeof(params), &sbt, static_cast<unsigned int>(grid.nx),
                           static_cast<unsigned int>(grid.ny), static_cast<unsigned int>(grid.nz)));
  CUDA_CHECK(cudaStreamSynchronize(stream));

  grid.distances.resize(numCells);
  CUDA_CHECK(cudaMemcpy(grid.distances.data(), reinterpret_cast<void *>(outputBuffer), numCells * sizeof(float),
                         cudaMemcpyDeviceToHost));

  cudaFree(reinterpret_cast<void *>(outputBuffer));
  cudaFree(reinterpret_cast<void *>(d_params));
  cudaFree(reinterpret_cast<void *>(d_rg));
  cudaFree(reinterpret_cast<void *>(d_ms));
  cudaFree(reinterpret_cast<void *>(d_hg));
  cudaFree(reinterpret_cast<void *>(gasBuffer));
  optixPipelineDestroy(pipeline);
  optixProgramGroupDestroy(hitPG);
  optixProgramGroupDestroy(missPG);
  optixProgramGroupDestroy(raygenPG);
  optixModuleDestroy(module);
  optixDeviceContextDestroy(context);

  return grid;
}

} // namespace italy
