#include "convert/sdf_baker.h"

#include <optix.h>
// optix_function_table_definition.h deliberately NOT included here — it
// defines a process-wide global (g_optixFunctionTable_*) and must appear in
// exactly one translation unit across the whole binary. optix_renderer.cpp
// already provides it; this file just needs the declarations from
// optix_stubs.h to call into that same shared table.
#include <optix_stack_size.h>
#include <optix_stubs.h>

#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <vector>

#include <sutil/vec_math.h>

#include "convert/tri_box_overlap.h"
#include "render/kernels/sdf_bake_params.h"
#include "render/optix_check.h"
#include "render_config.h" // generated by CMake: kSdfBakeOptixIRPath

// claudia: this builds and tears down its own OptixDeviceContext rather
// than sharing OptixRenderer's — baking runs once at load time, so the
// ~100-200ms of extra context/module setup is immaterial, and it keeps this
// file fully decoupled from OptixRenderer's internals (no shared-context
// plumbing across a header boundary for a one-shot preprocess). Revisit only
// if baking needs to happen repeatedly at interactive rates.

namespace italy {
namespace {

float3 toFloat3(const glm::vec3 &v) { return make_float3(v.x, v.y, v.z); }

std::vector<char> readFile(const char *path) {
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f)
    throw std::runtime_error(std::string("cannot open ") + path);
  const auto size = f.tellg();
  std::vector<char> data(static_cast<size_t>(size));
  f.seekg(0);
  f.read(data.data(), size);
  return data;
}

void logCallback(unsigned int level, const char *tag, const char *message, void *) {
  std::fprintf(stderr, "[optix-bake][%u][%s] %s\n", level, tag, message);
}

// glTF baseColorTexture is sRGB-encoded (baseColorFactor is linear); this
// CPU-side bake has no hardware sRGB decode the way the GPU texture path
// does, so it needs the standard sRGB EOTF explicitly — same reasoning and
// same formula as voxelize.cpp's own srgbToLinear, small enough (and
// self-contained enough — no shared state beyond the formula itself) that
// duplicating it here isn't worth a second header extraction the way
// tri_box_overlap.h's much larger SAT test was.
float srgbToLinear(float c) { return c <= 0.04045f ? c / 12.92f : std::pow((c + 0.055f) / 1.055f, 2.4f); }

glm::vec3 sampleColorNearest(const TextureAsset &tex, glm::vec2 uv) {
  auto wrap = [](float x) { return x - std::floor(x); };
  const int px = std::clamp(static_cast<int>(wrap(uv.x) * tex.width), 0, tex.width - 1);
  const int py = std::clamp(static_cast<int>(wrap(uv.y) * tex.height), 0, tex.height - 1);
  const size_t idx = (static_cast<size_t>(py) * tex.width + px) * 4;
  const glm::vec3 raw(tex.pixelsRGBA[idx] / 255.0f, tex.pixelsRGBA[idx + 1] / 255.0f, tex.pixelsRGBA[idx + 2] / 255.0f);
  if (!tex.srgb)
    return raw;
  return glm::vec3(srgbToLinear(raw.r), srgbToLinear(raw.g), srgbToLinear(raw.b));
}

// Per-triangle (baseColor, metallic, roughness), same material-resolution
// idiom voxelize.cpp's triangleColor() uses. Metallic/roughness only read
// the material's flat factors, not metallicRoughnessTexture — Phase 1's
// payoff is proving non-flat-tinted *color* out (the visible difference
// from the old single-scene-wide tintColor); per-texel metallic/roughness
// is a real refinement but not needed to ship this phase, and skipping it
// keeps this bake pass reading one texture per triangle (baseColor) instead
// of two.
struct CellMaterial {
  glm::vec3 baseColor;
  float metallic;
  float roughness;
};

CellMaterial triangleMaterial(const MeshAsset &mesh, size_t triangle) {
  const MaterialAsset &mat = mesh.materialForTriangle(triangle);
  glm::vec3 color = mat.baseColorFactor;
  const size_t base = triangle * 3;
  if (mat.baseColorTexture >= 0 && mat.baseColorTexture < static_cast<int>(mesh.textures.size()) &&
      base + 2 < mesh.uvs.size()) {
    const TextureAsset &tex = mesh.textures[mat.baseColorTexture];
    if (tex.width > 0 && tex.height > 0) {
      const glm::vec2 uv = (mesh.uvs[base] + mesh.uvs[base + 1] + mesh.uvs[base + 2]) / 3.0f;
      color = sampleColorNearest(tex, uv) * mat.baseColorFactor;
    }
  }
  return CellMaterial{color, mat.metallic, mat.roughness};
}

// Unified-SDF acceleration, Phase 1: rasterizes every triangle's material
// into every dense grid cell its bounding box overlaps — the same
// triBoxOverlap-driven algorithm voxelizeMesh() uses for VoxelGrid::colors
// (convert/voxelize.cpp), just writing into a dense nx*ny*nz array instead
// of a sparse occupied-cell map, since SdfGrid is dense already (see its own
// doc comment for why). Run as a CPU pass over the same mesh the GPU
// distance bake already traced, not folded into that OptiX kernel — see
// SdfGrid::baseColor's doc comment for why.
void bakePerCellMaterial(const MeshAsset &mesh, SdfGrid &grid) {
  const size_t numCells = static_cast<size_t>(grid.nx) * grid.ny * grid.nz;
  grid.baseColor.assign(numCells, glm::vec3(1.0f));
  grid.metallic.assign(numCells, 0.0f);
  grid.roughness.assign(numCells, 1.0f);
  if (numCells == 0)
    return;

  std::vector<glm::vec3> colorSum(numCells, glm::vec3(0.0f));
  std::vector<float> metallicSum(numCells, 0.0f), roughnessSum(numCells, 0.0f);
  std::vector<int> count(numCells, 0);

  const size_t triangleCount = mesh.positions.size() / 3;
  for (size_t t = 0; t < triangleCount; ++t) {
    const size_t base = t * 3;
    const glm::vec3 &p0 = mesh.positions[base];
    const glm::vec3 &p1 = mesh.positions[base + 1];
    const glm::vec3 &p2 = mesh.positions[base + 2];

    const glm::vec3 triMin = glm::min(glm::min(p0, p1), p2);
    const glm::vec3 triMax = glm::max(glm::max(p0, p1), p2);
    const glm::ivec3 res(grid.nx - 1, grid.ny - 1, grid.nz - 1);
    const glm::ivec3 cellMin =
        glm::clamp(glm::ivec3(glm::floor((triMin - grid.origin) / grid.voxelSize)), glm::ivec3(0), res);
    const glm::ivec3 cellMax =
        glm::clamp(glm::ivec3(glm::floor((triMax - grid.origin) / grid.voxelSize)), glm::ivec3(0), res);
    const CellMaterial mat = triangleMaterial(mesh, t);

    for (int z = cellMin.z; z <= cellMax.z; ++z) {
      for (int y = cellMin.y; y <= cellMax.y; ++y) {
        for (int x = cellMin.x; x <= cellMax.x; ++x) {
          const glm::vec3 center = grid.origin + (glm::vec3(x, y, z) + 0.5f) * grid.voxelSize;
          const glm::vec3 half(grid.voxelSize * 0.5f);
          if (!triBoxOverlap(center, half, p0, p1, p2))
            continue;
          const size_t idx = grid.index(x, y, z);
          colorSum[idx] += mat.baseColor;
          metallicSum[idx] += mat.metallic;
          roughnessSum[idx] += mat.roughness;
          count[idx] += 1;
        }
      }
    }
  }

  for (size_t i = 0; i < numCells; ++i) {
    if (count[i] == 0)
      continue; // leave the default (white, 0 metallic, 1 roughness) — see SdfGrid::baseColor's doc comment
    grid.baseColor[i] = colorSum[i] / static_cast<float>(count[i]);
    grid.metallic[i] = metallicSum[i] / static_cast<float>(count[i]);
    grid.roughness[i] = roughnessSum[i] / static_cast<float>(count[i]);
  }
}

template <typename T> struct SbtRecord {
  __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
  T data;
};

} // namespace

SdfGrid bakeSdf(const MeshAsset &mesh, int resolution) {
  SdfGrid grid;
  const glm::vec3 extent = mesh.boundsMax - mesh.boundsMin;
  const float longestAxis = std::max({extent.x, extent.y, extent.z, 1e-6f});
  grid.voxelSize = longestAxis / static_cast<float>(std::max(resolution, 1));

  // Pad the grid a couple of cells beyond the mesh's own bounding box so
  // sphere tracing has room to approach the surface from outside cleanly
  // rather than starting exactly at its edge.
  constexpr int kPad = 2;
  grid.origin = mesh.boundsMin - glm::vec3(grid.voxelSize * kPad);
  const glm::vec3 paddedExtent = extent + glm::vec3(grid.voxelSize * kPad * 2.0f);
  grid.nx = static_cast<int>(std::ceil(paddedExtent.x / grid.voxelSize)) + 1;
  grid.ny = static_cast<int>(std::ceil(paddedExtent.y / grid.voxelSize)) + 1;
  grid.nz = static_cast<int>(std::ceil(paddedExtent.z / grid.voxelSize)) + 1;

  OptixDeviceContext context = nullptr;
  CUDA_CHECK(cudaFree(nullptr));
  OPTIX_CHECK(optixInit());
  OptixDeviceContextOptions ctxOptions{};
  ctxOptions.logCallbackFunction = &logCallback;
  ctxOptions.logCallbackLevel = 3;
  OPTIX_CHECK(optixDeviceContextCreate(nullptr, &ctxOptions, &context));

  CUstream stream;
  CUDA_CHECK(cudaStreamCreate(&stream));

  // Triangle GAS for the mesh, traced directly (no IAS — nothing else in
  // this pass needs one, and BakeParams.meshHandle is typed to expect it).
  std::vector<float3> positions(mesh.positions.size());
  for (size_t i = 0; i < mesh.positions.size(); ++i)
    positions[i] = toFloat3(mesh.positions[i]);

  CUdeviceptr vertexBuffer;
  const size_t vbytes = positions.size() * sizeof(float3);
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&vertexBuffer), vbytes));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(vertexBuffer), positions.data(), vbytes, cudaMemcpyHostToDevice));

  OptixBuildInput input{};
  input.type = OPTIX_BUILD_INPUT_TYPE_TRIANGLES;
  input.triangleArray.vertexFormat = OPTIX_VERTEX_FORMAT_FLOAT3;
  input.triangleArray.vertexStrideInBytes = sizeof(float3);
  input.triangleArray.numVertices = static_cast<unsigned int>(positions.size());
  input.triangleArray.vertexBuffers = &vertexBuffer;
  static const uint32_t flags[1] = {OPTIX_GEOMETRY_FLAG_NONE};
  input.triangleArray.flags = flags;
  input.triangleArray.numSbtRecords = 1;

  OptixAccelBuildOptions accelOptions{};
  // Every cell of the grid fires ~160 distance rays plus up to 5x64 parity
  // rays into this one BVH, so traversal cost dominates the build cost by
  // orders of magnitude (doctrine rung 2). No ALLOW_RANDOM_VERTEX_ACCESS:
  // __closesthit__bake only reads optixGetRayTmax, never vertex data.
  accelOptions.buildFlags = OPTIX_BUILD_FLAG_PREFER_FAST_TRACE;
  accelOptions.operation = OPTIX_BUILD_OPERATION_BUILD;
  OptixAccelBufferSizes sizes{};
  OPTIX_CHECK(optixAccelComputeMemoryUsage(context, &accelOptions, &input, 1, &sizes));
  CUdeviceptr tempBuffer, gasBuffer;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&tempBuffer), sizes.tempSizeInBytes));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&gasBuffer), sizes.outputSizeInBytes));
  OptixTraversableHandle gasHandle;
  OPTIX_CHECK(optixAccelBuild(context, stream, &accelOptions, &input, 1, tempBuffer, sizes.tempSizeInBytes, gasBuffer,
                               sizes.outputSizeInBytes, &gasHandle, nullptr, 0));
  CUDA_CHECK(cudaStreamSynchronize(stream));
  cudaFree(reinterpret_cast<void *>(tempBuffer));
  cudaFree(reinterpret_cast<void *>(vertexBuffer));

  OptixPipelineCompileOptions pcOpts{};
  pcOpts.usesMotionBlur = false;
  pcOpts.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS; // raw GAS trace, no IAS
  pcOpts.numPayloadValues = 1;
  pcOpts.numAttributeValues = 2;
  pcOpts.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
  pcOpts.pipelineLaunchParamsVariableName = "params";
  pcOpts.usesPrimitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE;

  OptixModuleCompileOptions mcOpts{};
  mcOpts.optLevel = OPTIX_COMPILE_OPTIMIZATION_LEVEL_3;
  mcOpts.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;

  OptixModule module;
  const std::vector<char> ir = readFile(kSdfBakeOptixIRPath);
  OPTIX_CHECK_LOG(optixModuleCreate(context, &mcOpts, &pcOpts, ir.data(), ir.size(), LOG, &LOG_SIZE, &module));

  OptixProgramGroupOptions pgOpts{};
  OptixProgramGroup raygenPG, missPG, hitPG;

  OptixProgramGroupDesc rgDesc{};
  rgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
  rgDesc.raygen.module = module;
  rgDesc.raygen.entryFunctionName = "__raygen__bake_sdf";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &rgDesc, 1, &pgOpts, LOG, &LOG_SIZE, &raygenPG));

  OptixProgramGroupDesc msDesc{};
  msDesc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
  msDesc.miss.module = module;
  msDesc.miss.entryFunctionName = "__miss__bake";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &msDesc, 1, &pgOpts, LOG, &LOG_SIZE, &missPG));

  OptixProgramGroupDesc hgDesc{};
  hgDesc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
  hgDesc.hitgroup.moduleCH = module;
  hgDesc.hitgroup.entryFunctionNameCH = "__closesthit__bake";
  OPTIX_CHECK_LOG(optixProgramGroupCreate(context, &hgDesc, 1, &pgOpts, LOG, &LOG_SIZE, &hitPG));

  OptixProgramGroup groups[] = {raygenPG, missPG, hitPG};
  OptixPipelineLinkOptions linkOpts{};
  linkOpts.maxTraceDepth = 1; // raygen calls optixTrace directly, no nested tracing
  OptixPipeline pipeline;
  OPTIX_CHECK_LOG(optixPipelineCreate(context, &pcOpts, &linkOpts, groups, 3, LOG, &LOG_SIZE, &pipeline));
  OptixStackSizes stackSizes{};
  for (auto *g : groups)
    OPTIX_CHECK(optixUtilAccumulateStackSizes(g, &stackSizes, pipeline));
  uint32_t dcFromTraversal, dcFromState, contStack;
  OPTIX_CHECK(optixUtilComputeStackSizes(&stackSizes, 1, 0, 0, &dcFromTraversal, &dcFromState, &contStack));
  OPTIX_CHECK(optixPipelineSetStackSize(pipeline, dcFromTraversal, dcFromState, contStack, 1));

  SbtRecord<BakeRayGenData> rgRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(raygenPG, &rgRecord));
  SbtRecord<BakeMissData> msRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(missPG, &msRecord));
  SbtRecord<BakeHitGroupData> hgRecord{};
  OPTIX_CHECK(optixSbtRecordPackHeader(hitPG, &hgRecord));

  CUdeviceptr d_rg, d_ms, d_hg;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_rg), sizeof(rgRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_rg), &rgRecord, sizeof(rgRecord), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_ms), sizeof(msRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_ms), &msRecord, sizeof(msRecord), cudaMemcpyHostToDevice));
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_hg), sizeof(hgRecord)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_hg), &hgRecord, sizeof(hgRecord), cudaMemcpyHostToDevice));

  OptixShaderBindingTable sbt{};
  sbt.raygenRecord = d_rg;
  sbt.missRecordBase = d_ms;
  sbt.missRecordStrideInBytes = sizeof(msRecord);
  sbt.missRecordCount = 1;
  sbt.hitgroupRecordBase = d_hg;
  sbt.hitgroupRecordStrideInBytes = sizeof(hgRecord);
  sbt.hitgroupRecordCount = 1;

  const size_t numCells = static_cast<size_t>(grid.nx) * grid.ny * grid.nz;
  CUdeviceptr outputBuffer;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&outputBuffer), numCells * sizeof(float)));

  BakeParams params{};
  params.meshHandle = gasHandle;
  params.gridOrigin = toFloat3(grid.origin);
  params.voxelSize = grid.voxelSize;
  params.nx = static_cast<unsigned int>(grid.nx);
  params.ny = static_cast<unsigned int>(grid.ny);
  params.nz = static_cast<unsigned int>(grid.nz);
  params.output = reinterpret_cast<float *>(outputBuffer);

  CUdeviceptr d_params;
  CUDA_CHECK(cudaMalloc(reinterpret_cast<void **>(&d_params), sizeof(params)));
  CUDA_CHECK(cudaMemcpy(reinterpret_cast<void *>(d_params), &params, sizeof(params), cudaMemcpyHostToDevice));

  OPTIX_CHECK(optixLaunch(pipeline, stream, d_params, sizeof(params), &sbt, static_cast<unsigned int>(grid.nx),
                           static_cast<unsigned int>(grid.ny), static_cast<unsigned int>(grid.nz)));
  CUDA_CHECK(cudaStreamSynchronize(stream));

  grid.distances.resize(numCells);
  CUDA_CHECK(cudaMemcpy(grid.distances.data(), reinterpret_cast<void *>(outputBuffer), numCells * sizeof(float),
                         cudaMemcpyDeviceToHost));

  cudaFree(reinterpret_cast<void *>(outputBuffer));
  cudaFree(reinterpret_cast<void *>(d_params));
  cudaFree(reinterpret_cast<void *>(d_rg));
  cudaFree(reinterpret_cast<void *>(d_ms));
  cudaFree(reinterpret_cast<void *>(d_hg));
  cudaFree(reinterpret_cast<void *>(gasBuffer));
  optixPipelineDestroy(pipeline);
  optixProgramGroupDestroy(hitPG);
  optixProgramGroupDestroy(missPG);
  optixProgramGroupDestroy(raygenPG);
  optixModuleDestroy(module);
  optixDeviceContextDestroy(context);

  bakePerCellMaterial(mesh, grid);

  return grid;
}

} // namespace italy
